@startuml
class ProjectController{
}
class OrderController{
}

interface UserService{
void getUser();
}
interface ProjectService{
void addProject();
void delProject();
}
interface OrderService{
void addOrder();
void delOrder();
}

class ProjectServiceImpl{
void getUser();
void addProject();
void delProject();
}
class OrderServiceImpl{
void getUser();
void addOrder();
void delOrder();
}


ProjectController ..|> UserService
ProjectController ..|> ProjectService
OrderController ..|> UserService
OrderController ..|> OrderService

ProjectServiceImpl..>UserService
ProjectServiceImpl..>ProjectService
OrderServiceImpl..>UserService
OrderServiceImpl..>OrderService
@enduml