package com.enhui.netty.research.simple.common.proto;// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: msg.proto

public final class MsgProto {
  private MsgProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface DpMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:DpMessage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.DpMessage.DpMsgType msg_type = 1;</code>
     * @return The enum numeric value on the wire for msgType.
     */
    int getMsgTypeValue();
    /**
     * <code>.DpMessage.DpMsgType msg_type = 1;</code>
     * @return The msgType.
     */
    MsgProto.DpMessage.DpMsgType getMsgType();

    /**
     * <code>.FileContentCmd fileContentCmd = 2;</code>
     * @return Whether the fileContentCmd field is set.
     */
    boolean hasFileContentCmd();
    /**
     * <code>.FileContentCmd fileContentCmd = 2;</code>
     * @return The fileContentCmd.
     */
    MsgProto.FileContentCmd getFileContentCmd();
    /**
     * <code>.FileContentCmd fileContentCmd = 2;</code>
     */
    MsgProto.FileContentCmdOrBuilder getFileContentCmdOrBuilder();

    /**
     * <code>.FileContentResult fileContentResult = 3;</code>
     * @return Whether the fileContentResult field is set.
     */
    boolean hasFileContentResult();
    /**
     * <code>.FileContentResult fileContentResult = 3;</code>
     * @return The fileContentResult.
     */
    MsgProto.FileContentResult getFileContentResult();
    /**
     * <code>.FileContentResult fileContentResult = 3;</code>
     */
    MsgProto.FileContentResultOrBuilder getFileContentResultOrBuilder();

    public MsgProto.DpMessage.DataBodyCase getDataBodyCase();
  }
  /**
   * Protobuf type {@code DpMessage}
   */
  public static final class DpMessage extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:DpMessage)
      DpMessageOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use DpMessage.newBuilder() to construct.
    private DpMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private DpMessage() {
      msgType_ = 0;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new DpMessage();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return MsgProto.internal_static_DpMessage_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return MsgProto.internal_static_DpMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              MsgProto.DpMessage.class, MsgProto.DpMessage.Builder.class);
    }

    /**
     * Protobuf enum {@code DpMessage.DpMsgType}
     */
    public enum DpMsgType
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>FILE_CONTENT_CMD = 0;</code>
       */
      FILE_CONTENT_CMD(0),
      /**
       * <code>FILE_CONTENT_RESULT = 1;</code>
       */
      FILE_CONTENT_RESULT(1),
      UNRECOGNIZED(-1),
      ;

      /**
       * <code>FILE_CONTENT_CMD = 0;</code>
       */
      public static final int FILE_CONTENT_CMD_VALUE = 0;
      /**
       * <code>FILE_CONTENT_RESULT = 1;</code>
       */
      public static final int FILE_CONTENT_RESULT_VALUE = 1;


      public final int getNumber() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalArgumentException(
              "Can't get the number of an unknown enum value.");
        }
        return value;
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static DpMsgType valueOf(int value) {
        return forNumber(value);
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       */
      public static DpMsgType forNumber(int value) {
        switch (value) {
          case 0: return FILE_CONTENT_CMD;
          case 1: return FILE_CONTENT_RESULT;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<DpMsgType>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          DpMsgType> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<DpMsgType>() {
              public DpMsgType findValueByNumber(int number) {
                return DpMsgType.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalStateException(
              "Can't get the descriptor of an unrecognized enum value.");
        }
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return MsgProto.DpMessage.getDescriptor().getEnumTypes().get(0);
      }

      private static final DpMsgType[] VALUES = values();

      public static DpMsgType valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        if (desc.getIndex() == -1) {
          return UNRECOGNIZED;
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private DpMsgType(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:DpMessage.DpMsgType)
    }

    private int dataBodyCase_ = 0;
    private java.lang.Object dataBody_;
    public enum DataBodyCase
        implements com.google.protobuf.Internal.EnumLite,
            com.google.protobuf.AbstractMessage.InternalOneOfEnum {
      FILECONTENTCMD(2),
      FILECONTENTRESULT(3),
      DATABODY_NOT_SET(0);
      private final int value;
      private DataBodyCase(int value) {
        this.value = value;
      }
      /**
       * @param value The number of the enum to look for.
       * @return The enum associated with the given number.
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static DataBodyCase valueOf(int value) {
        return forNumber(value);
      }

      public static DataBodyCase forNumber(int value) {
        switch (value) {
          case 2: return FILECONTENTCMD;
          case 3: return FILECONTENTRESULT;
          case 0: return DATABODY_NOT_SET;
          default: return null;
        }
      }
      public int getNumber() {
        return this.value;
      }
    };

    public DataBodyCase
    getDataBodyCase() {
      return DataBodyCase.forNumber(
          dataBodyCase_);
    }

    public static final int MSG_TYPE_FIELD_NUMBER = 1;
    private int msgType_ = 0;
    /**
     * <code>.DpMessage.DpMsgType msg_type = 1;</code>
     * @return The enum numeric value on the wire for msgType.
     */
    @java.lang.Override public int getMsgTypeValue() {
      return msgType_;
    }
    /**
     * <code>.DpMessage.DpMsgType msg_type = 1;</code>
     * @return The msgType.
     */
    @java.lang.Override public MsgProto.DpMessage.DpMsgType getMsgType() {
      MsgProto.DpMessage.DpMsgType result = MsgProto.DpMessage.DpMsgType.forNumber(msgType_);
      return result == null ? MsgProto.DpMessage.DpMsgType.UNRECOGNIZED : result;
    }

    public static final int FILECONTENTCMD_FIELD_NUMBER = 2;
    /**
     * <code>.FileContentCmd fileContentCmd = 2;</code>
     * @return Whether the fileContentCmd field is set.
     */
    @java.lang.Override
    public boolean hasFileContentCmd() {
      return dataBodyCase_ == 2;
    }
    /**
     * <code>.FileContentCmd fileContentCmd = 2;</code>
     * @return The fileContentCmd.
     */
    @java.lang.Override
    public MsgProto.FileContentCmd getFileContentCmd() {
      if (dataBodyCase_ == 2) {
         return (MsgProto.FileContentCmd) dataBody_;
      }
      return MsgProto.FileContentCmd.getDefaultInstance();
    }
    /**
     * <code>.FileContentCmd fileContentCmd = 2;</code>
     */
    @java.lang.Override
    public MsgProto.FileContentCmdOrBuilder getFileContentCmdOrBuilder() {
      if (dataBodyCase_ == 2) {
         return (MsgProto.FileContentCmd) dataBody_;
      }
      return MsgProto.FileContentCmd.getDefaultInstance();
    }

    public static final int FILECONTENTRESULT_FIELD_NUMBER = 3;
    /**
     * <code>.FileContentResult fileContentResult = 3;</code>
     * @return Whether the fileContentResult field is set.
     */
    @java.lang.Override
    public boolean hasFileContentResult() {
      return dataBodyCase_ == 3;
    }
    /**
     * <code>.FileContentResult fileContentResult = 3;</code>
     * @return The fileContentResult.
     */
    @java.lang.Override
    public MsgProto.FileContentResult getFileContentResult() {
      if (dataBodyCase_ == 3) {
         return (MsgProto.FileContentResult) dataBody_;
      }
      return MsgProto.FileContentResult.getDefaultInstance();
    }
    /**
     * <code>.FileContentResult fileContentResult = 3;</code>
     */
    @java.lang.Override
    public MsgProto.FileContentResultOrBuilder getFileContentResultOrBuilder() {
      if (dataBodyCase_ == 3) {
         return (MsgProto.FileContentResult) dataBody_;
      }
      return MsgProto.FileContentResult.getDefaultInstance();
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (msgType_ != MsgProto.DpMessage.DpMsgType.FILE_CONTENT_CMD.getNumber()) {
        output.writeEnum(1, msgType_);
      }
      if (dataBodyCase_ == 2) {
        output.writeMessage(2, (MsgProto.FileContentCmd) dataBody_);
      }
      if (dataBodyCase_ == 3) {
        output.writeMessage(3, (MsgProto.FileContentResult) dataBody_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (msgType_ != MsgProto.DpMessage.DpMsgType.FILE_CONTENT_CMD.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, msgType_);
      }
      if (dataBodyCase_ == 2) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, (MsgProto.FileContentCmd) dataBody_);
      }
      if (dataBodyCase_ == 3) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, (MsgProto.FileContentResult) dataBody_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof MsgProto.DpMessage)) {
        return super.equals(obj);
      }
      MsgProto.DpMessage other = (MsgProto.DpMessage) obj;

      if (msgType_ != other.msgType_) return false;
      if (!getDataBodyCase().equals(other.getDataBodyCase())) return false;
      switch (dataBodyCase_) {
        case 2:
          if (!getFileContentCmd()
              .equals(other.getFileContentCmd())) return false;
          break;
        case 3:
          if (!getFileContentResult()
              .equals(other.getFileContentResult())) return false;
          break;
        case 0:
        default:
      }
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + MSG_TYPE_FIELD_NUMBER;
      hash = (53 * hash) + msgType_;
      switch (dataBodyCase_) {
        case 2:
          hash = (37 * hash) + FILECONTENTCMD_FIELD_NUMBER;
          hash = (53 * hash) + getFileContentCmd().hashCode();
          break;
        case 3:
          hash = (37 * hash) + FILECONTENTRESULT_FIELD_NUMBER;
          hash = (53 * hash) + getFileContentResult().hashCode();
          break;
        case 0:
        default:
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static MsgProto.DpMessage parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static MsgProto.DpMessage parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static MsgProto.DpMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static MsgProto.DpMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static MsgProto.DpMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static MsgProto.DpMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static MsgProto.DpMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static MsgProto.DpMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static MsgProto.DpMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static MsgProto.DpMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static MsgProto.DpMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static MsgProto.DpMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(MsgProto.DpMessage prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code DpMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:DpMessage)
        MsgProto.DpMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return MsgProto.internal_static_DpMessage_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return MsgProto.internal_static_DpMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                MsgProto.DpMessage.class, MsgProto.DpMessage.Builder.class);
      }

      // Construct using MsgProto.DpMessage.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        msgType_ = 0;
        if (fileContentCmdBuilder_ != null) {
          fileContentCmdBuilder_.clear();
        }
        if (fileContentResultBuilder_ != null) {
          fileContentResultBuilder_.clear();
        }
        dataBodyCase_ = 0;
        dataBody_ = null;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return MsgProto.internal_static_DpMessage_descriptor;
      }

      @java.lang.Override
      public MsgProto.DpMessage getDefaultInstanceForType() {
        return MsgProto.DpMessage.getDefaultInstance();
      }

      @java.lang.Override
      public MsgProto.DpMessage build() {
        MsgProto.DpMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public MsgProto.DpMessage buildPartial() {
        MsgProto.DpMessage result = new MsgProto.DpMessage(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        buildPartialOneofs(result);
        onBuilt();
        return result;
      }

      private void buildPartial0(MsgProto.DpMessage result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.msgType_ = msgType_;
        }
      }

      private void buildPartialOneofs(MsgProto.DpMessage result) {
        result.dataBodyCase_ = dataBodyCase_;
        result.dataBody_ = this.dataBody_;
        if (dataBodyCase_ == 2 &&
            fileContentCmdBuilder_ != null) {
          result.dataBody_ = fileContentCmdBuilder_.build();
        }
        if (dataBodyCase_ == 3 &&
            fileContentResultBuilder_ != null) {
          result.dataBody_ = fileContentResultBuilder_.build();
        }
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof MsgProto.DpMessage) {
          return mergeFrom((MsgProto.DpMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(MsgProto.DpMessage other) {
        if (other == MsgProto.DpMessage.getDefaultInstance()) return this;
        if (other.msgType_ != 0) {
          setMsgTypeValue(other.getMsgTypeValue());
        }
        switch (other.getDataBodyCase()) {
          case FILECONTENTCMD: {
            mergeFileContentCmd(other.getFileContentCmd());
            break;
          }
          case FILECONTENTRESULT: {
            mergeFileContentResult(other.getFileContentResult());
            break;
          }
          case DATABODY_NOT_SET: {
            break;
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                msgType_ = input.readEnum();
                bitField0_ |= 0x00000001;
                break;
              } // case 8
              case 18: {
                input.readMessage(
                    getFileContentCmdFieldBuilder().getBuilder(),
                    extensionRegistry);
                dataBodyCase_ = 2;
                break;
              } // case 18
              case 26: {
                input.readMessage(
                    getFileContentResultFieldBuilder().getBuilder(),
                    extensionRegistry);
                dataBodyCase_ = 3;
                break;
              } // case 26
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int dataBodyCase_ = 0;
      private java.lang.Object dataBody_;
      public DataBodyCase
          getDataBodyCase() {
        return DataBodyCase.forNumber(
            dataBodyCase_);
      }

      public Builder clearDataBody() {
        dataBodyCase_ = 0;
        dataBody_ = null;
        onChanged();
        return this;
      }

      private int bitField0_;

      private int msgType_ = 0;
      /**
       * <code>.DpMessage.DpMsgType msg_type = 1;</code>
       * @return The enum numeric value on the wire for msgType.
       */
      @java.lang.Override public int getMsgTypeValue() {
        return msgType_;
      }
      /**
       * <code>.DpMessage.DpMsgType msg_type = 1;</code>
       * @param value The enum numeric value on the wire for msgType to set.
       * @return This builder for chaining.
       */
      public Builder setMsgTypeValue(int value) {
        msgType_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>.DpMessage.DpMsgType msg_type = 1;</code>
       * @return The msgType.
       */
      @java.lang.Override
      public MsgProto.DpMessage.DpMsgType getMsgType() {
        MsgProto.DpMessage.DpMsgType result = MsgProto.DpMessage.DpMsgType.forNumber(msgType_);
        return result == null ? MsgProto.DpMessage.DpMsgType.UNRECOGNIZED : result;
      }
      /**
       * <code>.DpMessage.DpMsgType msg_type = 1;</code>
       * @param value The msgType to set.
       * @return This builder for chaining.
       */
      public Builder setMsgType(MsgProto.DpMessage.DpMsgType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        msgType_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.DpMessage.DpMsgType msg_type = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearMsgType() {
        bitField0_ = (bitField0_ & ~0x00000001);
        msgType_ = 0;
        onChanged();
        return this;
      }

      private com.google.protobuf.SingleFieldBuilderV3<
          MsgProto.FileContentCmd, MsgProto.FileContentCmd.Builder, MsgProto.FileContentCmdOrBuilder> fileContentCmdBuilder_;
      /**
       * <code>.FileContentCmd fileContentCmd = 2;</code>
       * @return Whether the fileContentCmd field is set.
       */
      @java.lang.Override
      public boolean hasFileContentCmd() {
        return dataBodyCase_ == 2;
      }
      /**
       * <code>.FileContentCmd fileContentCmd = 2;</code>
       * @return The fileContentCmd.
       */
      @java.lang.Override
      public MsgProto.FileContentCmd getFileContentCmd() {
        if (fileContentCmdBuilder_ == null) {
          if (dataBodyCase_ == 2) {
            return (MsgProto.FileContentCmd) dataBody_;
          }
          return MsgProto.FileContentCmd.getDefaultInstance();
        } else {
          if (dataBodyCase_ == 2) {
            return fileContentCmdBuilder_.getMessage();
          }
          return MsgProto.FileContentCmd.getDefaultInstance();
        }
      }
      /**
       * <code>.FileContentCmd fileContentCmd = 2;</code>
       */
      public Builder setFileContentCmd(MsgProto.FileContentCmd value) {
        if (fileContentCmdBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          dataBody_ = value;
          onChanged();
        } else {
          fileContentCmdBuilder_.setMessage(value);
        }
        dataBodyCase_ = 2;
        return this;
      }
      /**
       * <code>.FileContentCmd fileContentCmd = 2;</code>
       */
      public Builder setFileContentCmd(
          MsgProto.FileContentCmd.Builder builderForValue) {
        if (fileContentCmdBuilder_ == null) {
          dataBody_ = builderForValue.build();
          onChanged();
        } else {
          fileContentCmdBuilder_.setMessage(builderForValue.build());
        }
        dataBodyCase_ = 2;
        return this;
      }
      /**
       * <code>.FileContentCmd fileContentCmd = 2;</code>
       */
      public Builder mergeFileContentCmd(MsgProto.FileContentCmd value) {
        if (fileContentCmdBuilder_ == null) {
          if (dataBodyCase_ == 2 &&
              dataBody_ != MsgProto.FileContentCmd.getDefaultInstance()) {
            dataBody_ = MsgProto.FileContentCmd.newBuilder((MsgProto.FileContentCmd) dataBody_)
                .mergeFrom(value).buildPartial();
          } else {
            dataBody_ = value;
          }
          onChanged();
        } else {
          if (dataBodyCase_ == 2) {
            fileContentCmdBuilder_.mergeFrom(value);
          } else {
            fileContentCmdBuilder_.setMessage(value);
          }
        }
        dataBodyCase_ = 2;
        return this;
      }
      /**
       * <code>.FileContentCmd fileContentCmd = 2;</code>
       */
      public Builder clearFileContentCmd() {
        if (fileContentCmdBuilder_ == null) {
          if (dataBodyCase_ == 2) {
            dataBodyCase_ = 0;
            dataBody_ = null;
            onChanged();
          }
        } else {
          if (dataBodyCase_ == 2) {
            dataBodyCase_ = 0;
            dataBody_ = null;
          }
          fileContentCmdBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>.FileContentCmd fileContentCmd = 2;</code>
       */
      public MsgProto.FileContentCmd.Builder getFileContentCmdBuilder() {
        return getFileContentCmdFieldBuilder().getBuilder();
      }
      /**
       * <code>.FileContentCmd fileContentCmd = 2;</code>
       */
      @java.lang.Override
      public MsgProto.FileContentCmdOrBuilder getFileContentCmdOrBuilder() {
        if ((dataBodyCase_ == 2) && (fileContentCmdBuilder_ != null)) {
          return fileContentCmdBuilder_.getMessageOrBuilder();
        } else {
          if (dataBodyCase_ == 2) {
            return (MsgProto.FileContentCmd) dataBody_;
          }
          return MsgProto.FileContentCmd.getDefaultInstance();
        }
      }
      /**
       * <code>.FileContentCmd fileContentCmd = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          MsgProto.FileContentCmd, MsgProto.FileContentCmd.Builder, MsgProto.FileContentCmdOrBuilder> 
          getFileContentCmdFieldBuilder() {
        if (fileContentCmdBuilder_ == null) {
          if (!(dataBodyCase_ == 2)) {
            dataBody_ = MsgProto.FileContentCmd.getDefaultInstance();
          }
          fileContentCmdBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              MsgProto.FileContentCmd, MsgProto.FileContentCmd.Builder, MsgProto.FileContentCmdOrBuilder>(
                  (MsgProto.FileContentCmd) dataBody_,
                  getParentForChildren(),
                  isClean());
          dataBody_ = null;
        }
        dataBodyCase_ = 2;
        onChanged();
        return fileContentCmdBuilder_;
      }

      private com.google.protobuf.SingleFieldBuilderV3<
          MsgProto.FileContentResult, MsgProto.FileContentResult.Builder, MsgProto.FileContentResultOrBuilder> fileContentResultBuilder_;
      /**
       * <code>.FileContentResult fileContentResult = 3;</code>
       * @return Whether the fileContentResult field is set.
       */
      @java.lang.Override
      public boolean hasFileContentResult() {
        return dataBodyCase_ == 3;
      }
      /**
       * <code>.FileContentResult fileContentResult = 3;</code>
       * @return The fileContentResult.
       */
      @java.lang.Override
      public MsgProto.FileContentResult getFileContentResult() {
        if (fileContentResultBuilder_ == null) {
          if (dataBodyCase_ == 3) {
            return (MsgProto.FileContentResult) dataBody_;
          }
          return MsgProto.FileContentResult.getDefaultInstance();
        } else {
          if (dataBodyCase_ == 3) {
            return fileContentResultBuilder_.getMessage();
          }
          return MsgProto.FileContentResult.getDefaultInstance();
        }
      }
      /**
       * <code>.FileContentResult fileContentResult = 3;</code>
       */
      public Builder setFileContentResult(MsgProto.FileContentResult value) {
        if (fileContentResultBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          dataBody_ = value;
          onChanged();
        } else {
          fileContentResultBuilder_.setMessage(value);
        }
        dataBodyCase_ = 3;
        return this;
      }
      /**
       * <code>.FileContentResult fileContentResult = 3;</code>
       */
      public Builder setFileContentResult(
          MsgProto.FileContentResult.Builder builderForValue) {
        if (fileContentResultBuilder_ == null) {
          dataBody_ = builderForValue.build();
          onChanged();
        } else {
          fileContentResultBuilder_.setMessage(builderForValue.build());
        }
        dataBodyCase_ = 3;
        return this;
      }
      /**
       * <code>.FileContentResult fileContentResult = 3;</code>
       */
      public Builder mergeFileContentResult(MsgProto.FileContentResult value) {
        if (fileContentResultBuilder_ == null) {
          if (dataBodyCase_ == 3 &&
              dataBody_ != MsgProto.FileContentResult.getDefaultInstance()) {
            dataBody_ = MsgProto.FileContentResult.newBuilder((MsgProto.FileContentResult) dataBody_)
                .mergeFrom(value).buildPartial();
          } else {
            dataBody_ = value;
          }
          onChanged();
        } else {
          if (dataBodyCase_ == 3) {
            fileContentResultBuilder_.mergeFrom(value);
          } else {
            fileContentResultBuilder_.setMessage(value);
          }
        }
        dataBodyCase_ = 3;
        return this;
      }
      /**
       * <code>.FileContentResult fileContentResult = 3;</code>
       */
      public Builder clearFileContentResult() {
        if (fileContentResultBuilder_ == null) {
          if (dataBodyCase_ == 3) {
            dataBodyCase_ = 0;
            dataBody_ = null;
            onChanged();
          }
        } else {
          if (dataBodyCase_ == 3) {
            dataBodyCase_ = 0;
            dataBody_ = null;
          }
          fileContentResultBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>.FileContentResult fileContentResult = 3;</code>
       */
      public MsgProto.FileContentResult.Builder getFileContentResultBuilder() {
        return getFileContentResultFieldBuilder().getBuilder();
      }
      /**
       * <code>.FileContentResult fileContentResult = 3;</code>
       */
      @java.lang.Override
      public MsgProto.FileContentResultOrBuilder getFileContentResultOrBuilder() {
        if ((dataBodyCase_ == 3) && (fileContentResultBuilder_ != null)) {
          return fileContentResultBuilder_.getMessageOrBuilder();
        } else {
          if (dataBodyCase_ == 3) {
            return (MsgProto.FileContentResult) dataBody_;
          }
          return MsgProto.FileContentResult.getDefaultInstance();
        }
      }
      /**
       * <code>.FileContentResult fileContentResult = 3;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          MsgProto.FileContentResult, MsgProto.FileContentResult.Builder, MsgProto.FileContentResultOrBuilder> 
          getFileContentResultFieldBuilder() {
        if (fileContentResultBuilder_ == null) {
          if (!(dataBodyCase_ == 3)) {
            dataBody_ = MsgProto.FileContentResult.getDefaultInstance();
          }
          fileContentResultBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              MsgProto.FileContentResult, MsgProto.FileContentResult.Builder, MsgProto.FileContentResultOrBuilder>(
                  (MsgProto.FileContentResult) dataBody_,
                  getParentForChildren(),
                  isClean());
          dataBody_ = null;
        }
        dataBodyCase_ = 3;
        onChanged();
        return fileContentResultBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:DpMessage)
    }

    // @@protoc_insertion_point(class_scope:DpMessage)
    private static final MsgProto.DpMessage DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new MsgProto.DpMessage();
    }

    public static MsgProto.DpMessage getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<DpMessage>
        PARSER = new com.google.protobuf.AbstractParser<DpMessage>() {
      @java.lang.Override
      public DpMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<DpMessage> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<DpMessage> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public MsgProto.DpMessage getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface FileContentCmdOrBuilder extends
      // @@protoc_insertion_point(interface_extends:FileContentCmd)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * 文件名称
     * </pre>
     *
     * <code>string fileName = 1;</code>
     * @return The fileName.
     */
    java.lang.String getFileName();
    /**
     * <pre>
     * 文件名称
     * </pre>
     *
     * <code>string fileName = 1;</code>
     * @return The bytes for fileName.
     */
    com.google.protobuf.ByteString
        getFileNameBytes();
  }
  /**
   * Protobuf type {@code FileContentCmd}
   */
  public static final class FileContentCmd extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:FileContentCmd)
      FileContentCmdOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use FileContentCmd.newBuilder() to construct.
    private FileContentCmd(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private FileContentCmd() {
      fileName_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new FileContentCmd();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return MsgProto.internal_static_FileContentCmd_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return MsgProto.internal_static_FileContentCmd_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              MsgProto.FileContentCmd.class, MsgProto.FileContentCmd.Builder.class);
    }

    public static final int FILENAME_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private volatile java.lang.Object fileName_ = "";
    /**
     * <pre>
     * 文件名称
     * </pre>
     *
     * <code>string fileName = 1;</code>
     * @return The fileName.
     */
    @java.lang.Override
    public java.lang.String getFileName() {
      java.lang.Object ref = fileName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        fileName_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * 文件名称
     * </pre>
     *
     * <code>string fileName = 1;</code>
     * @return The bytes for fileName.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getFileNameBytes() {
      java.lang.Object ref = fileName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        fileName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(fileName_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, fileName_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(fileName_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, fileName_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof MsgProto.FileContentCmd)) {
        return super.equals(obj);
      }
      MsgProto.FileContentCmd other = (MsgProto.FileContentCmd) obj;

      if (!getFileName()
          .equals(other.getFileName())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + FILENAME_FIELD_NUMBER;
      hash = (53 * hash) + getFileName().hashCode();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static MsgProto.FileContentCmd parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static MsgProto.FileContentCmd parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static MsgProto.FileContentCmd parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static MsgProto.FileContentCmd parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static MsgProto.FileContentCmd parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static MsgProto.FileContentCmd parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static MsgProto.FileContentCmd parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static MsgProto.FileContentCmd parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static MsgProto.FileContentCmd parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static MsgProto.FileContentCmd parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static MsgProto.FileContentCmd parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static MsgProto.FileContentCmd parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(MsgProto.FileContentCmd prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code FileContentCmd}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:FileContentCmd)
        MsgProto.FileContentCmdOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return MsgProto.internal_static_FileContentCmd_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return MsgProto.internal_static_FileContentCmd_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                MsgProto.FileContentCmd.class, MsgProto.FileContentCmd.Builder.class);
      }

      // Construct using MsgProto.FileContentCmd.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        fileName_ = "";
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return MsgProto.internal_static_FileContentCmd_descriptor;
      }

      @java.lang.Override
      public MsgProto.FileContentCmd getDefaultInstanceForType() {
        return MsgProto.FileContentCmd.getDefaultInstance();
      }

      @java.lang.Override
      public MsgProto.FileContentCmd build() {
        MsgProto.FileContentCmd result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public MsgProto.FileContentCmd buildPartial() {
        MsgProto.FileContentCmd result = new MsgProto.FileContentCmd(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(MsgProto.FileContentCmd result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.fileName_ = fileName_;
        }
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof MsgProto.FileContentCmd) {
          return mergeFrom((MsgProto.FileContentCmd)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(MsgProto.FileContentCmd other) {
        if (other == MsgProto.FileContentCmd.getDefaultInstance()) return this;
        if (!other.getFileName().isEmpty()) {
          fileName_ = other.fileName_;
          bitField0_ |= 0x00000001;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                fileName_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.lang.Object fileName_ = "";
      /**
       * <pre>
       * 文件名称
       * </pre>
       *
       * <code>string fileName = 1;</code>
       * @return The fileName.
       */
      public java.lang.String getFileName() {
        java.lang.Object ref = fileName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          fileName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * 文件名称
       * </pre>
       *
       * <code>string fileName = 1;</code>
       * @return The bytes for fileName.
       */
      public com.google.protobuf.ByteString
          getFileNameBytes() {
        java.lang.Object ref = fileName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          fileName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * 文件名称
       * </pre>
       *
       * <code>string fileName = 1;</code>
       * @param value The fileName to set.
       * @return This builder for chaining.
       */
      public Builder setFileName(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        fileName_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 文件名称
       * </pre>
       *
       * <code>string fileName = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearFileName() {
        fileName_ = getDefaultInstance().getFileName();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 文件名称
       * </pre>
       *
       * <code>string fileName = 1;</code>
       * @param value The bytes for fileName to set.
       * @return This builder for chaining.
       */
      public Builder setFileNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        fileName_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:FileContentCmd)
    }

    // @@protoc_insertion_point(class_scope:FileContentCmd)
    private static final MsgProto.FileContentCmd DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new MsgProto.FileContentCmd();
    }

    public static MsgProto.FileContentCmd getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<FileContentCmd>
        PARSER = new com.google.protobuf.AbstractParser<FileContentCmd>() {
      @java.lang.Override
      public FileContentCmd parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<FileContentCmd> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<FileContentCmd> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public MsgProto.FileContentCmd getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface FileContentResultOrBuilder extends
      // @@protoc_insertion_point(interface_extends:FileContentResult)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * 文件名称
     * </pre>
     *
     * <code>string fileName = 1;</code>
     * @return The fileName.
     */
    java.lang.String getFileName();
    /**
     * <pre>
     * 文件名称
     * </pre>
     *
     * <code>string fileName = 1;</code>
     * @return The bytes for fileName.
     */
    com.google.protobuf.ByteString
        getFileNameBytes();

    /**
     * <pre>
     * 文件内容
     * </pre>
     *
     * <code>string fileContent = 2;</code>
     * @return The fileContent.
     */
    java.lang.String getFileContent();
    /**
     * <pre>
     * 文件内容
     * </pre>
     *
     * <code>string fileContent = 2;</code>
     * @return The bytes for fileContent.
     */
    com.google.protobuf.ByteString
        getFileContentBytes();
  }
  /**
   * Protobuf type {@code FileContentResult}
   */
  public static final class FileContentResult extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:FileContentResult)
      FileContentResultOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use FileContentResult.newBuilder() to construct.
    private FileContentResult(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private FileContentResult() {
      fileName_ = "";
      fileContent_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new FileContentResult();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return MsgProto.internal_static_FileContentResult_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return MsgProto.internal_static_FileContentResult_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              MsgProto.FileContentResult.class, MsgProto.FileContentResult.Builder.class);
    }

    public static final int FILENAME_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private volatile java.lang.Object fileName_ = "";
    /**
     * <pre>
     * 文件名称
     * </pre>
     *
     * <code>string fileName = 1;</code>
     * @return The fileName.
     */
    @java.lang.Override
    public java.lang.String getFileName() {
      java.lang.Object ref = fileName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        fileName_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * 文件名称
     * </pre>
     *
     * <code>string fileName = 1;</code>
     * @return The bytes for fileName.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getFileNameBytes() {
      java.lang.Object ref = fileName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        fileName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int FILECONTENT_FIELD_NUMBER = 2;
    @SuppressWarnings("serial")
    private volatile java.lang.Object fileContent_ = "";
    /**
     * <pre>
     * 文件内容
     * </pre>
     *
     * <code>string fileContent = 2;</code>
     * @return The fileContent.
     */
    @java.lang.Override
    public java.lang.String getFileContent() {
      java.lang.Object ref = fileContent_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        fileContent_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * 文件内容
     * </pre>
     *
     * <code>string fileContent = 2;</code>
     * @return The bytes for fileContent.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getFileContentBytes() {
      java.lang.Object ref = fileContent_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        fileContent_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(fileName_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, fileName_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(fileContent_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, fileContent_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(fileName_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, fileName_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(fileContent_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, fileContent_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof MsgProto.FileContentResult)) {
        return super.equals(obj);
      }
      MsgProto.FileContentResult other = (MsgProto.FileContentResult) obj;

      if (!getFileName()
          .equals(other.getFileName())) return false;
      if (!getFileContent()
          .equals(other.getFileContent())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + FILENAME_FIELD_NUMBER;
      hash = (53 * hash) + getFileName().hashCode();
      hash = (37 * hash) + FILECONTENT_FIELD_NUMBER;
      hash = (53 * hash) + getFileContent().hashCode();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static MsgProto.FileContentResult parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static MsgProto.FileContentResult parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static MsgProto.FileContentResult parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static MsgProto.FileContentResult parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static MsgProto.FileContentResult parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static MsgProto.FileContentResult parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static MsgProto.FileContentResult parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static MsgProto.FileContentResult parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static MsgProto.FileContentResult parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static MsgProto.FileContentResult parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static MsgProto.FileContentResult parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static MsgProto.FileContentResult parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(MsgProto.FileContentResult prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code FileContentResult}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:FileContentResult)
        MsgProto.FileContentResultOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return MsgProto.internal_static_FileContentResult_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return MsgProto.internal_static_FileContentResult_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                MsgProto.FileContentResult.class, MsgProto.FileContentResult.Builder.class);
      }

      // Construct using MsgProto.FileContentResult.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        fileName_ = "";
        fileContent_ = "";
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return MsgProto.internal_static_FileContentResult_descriptor;
      }

      @java.lang.Override
      public MsgProto.FileContentResult getDefaultInstanceForType() {
        return MsgProto.FileContentResult.getDefaultInstance();
      }

      @java.lang.Override
      public MsgProto.FileContentResult build() {
        MsgProto.FileContentResult result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public MsgProto.FileContentResult buildPartial() {
        MsgProto.FileContentResult result = new MsgProto.FileContentResult(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(MsgProto.FileContentResult result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.fileName_ = fileName_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.fileContent_ = fileContent_;
        }
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof MsgProto.FileContentResult) {
          return mergeFrom((MsgProto.FileContentResult)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(MsgProto.FileContentResult other) {
        if (other == MsgProto.FileContentResult.getDefaultInstance()) return this;
        if (!other.getFileName().isEmpty()) {
          fileName_ = other.fileName_;
          bitField0_ |= 0x00000001;
          onChanged();
        }
        if (!other.getFileContent().isEmpty()) {
          fileContent_ = other.fileContent_;
          bitField0_ |= 0x00000002;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                fileName_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              case 18: {
                fileContent_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000002;
                break;
              } // case 18
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.lang.Object fileName_ = "";
      /**
       * <pre>
       * 文件名称
       * </pre>
       *
       * <code>string fileName = 1;</code>
       * @return The fileName.
       */
      public java.lang.String getFileName() {
        java.lang.Object ref = fileName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          fileName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * 文件名称
       * </pre>
       *
       * <code>string fileName = 1;</code>
       * @return The bytes for fileName.
       */
      public com.google.protobuf.ByteString
          getFileNameBytes() {
        java.lang.Object ref = fileName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          fileName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * 文件名称
       * </pre>
       *
       * <code>string fileName = 1;</code>
       * @param value The fileName to set.
       * @return This builder for chaining.
       */
      public Builder setFileName(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        fileName_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 文件名称
       * </pre>
       *
       * <code>string fileName = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearFileName() {
        fileName_ = getDefaultInstance().getFileName();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 文件名称
       * </pre>
       *
       * <code>string fileName = 1;</code>
       * @param value The bytes for fileName to set.
       * @return This builder for chaining.
       */
      public Builder setFileNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        fileName_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }

      private java.lang.Object fileContent_ = "";
      /**
       * <pre>
       * 文件内容
       * </pre>
       *
       * <code>string fileContent = 2;</code>
       * @return The fileContent.
       */
      public java.lang.String getFileContent() {
        java.lang.Object ref = fileContent_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          fileContent_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * 文件内容
       * </pre>
       *
       * <code>string fileContent = 2;</code>
       * @return The bytes for fileContent.
       */
      public com.google.protobuf.ByteString
          getFileContentBytes() {
        java.lang.Object ref = fileContent_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          fileContent_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * 文件内容
       * </pre>
       *
       * <code>string fileContent = 2;</code>
       * @param value The fileContent to set.
       * @return This builder for chaining.
       */
      public Builder setFileContent(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        fileContent_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 文件内容
       * </pre>
       *
       * <code>string fileContent = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearFileContent() {
        fileContent_ = getDefaultInstance().getFileContent();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 文件内容
       * </pre>
       *
       * <code>string fileContent = 2;</code>
       * @param value The bytes for fileContent to set.
       * @return This builder for chaining.
       */
      public Builder setFileContentBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        fileContent_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:FileContentResult)
    }

    // @@protoc_insertion_point(class_scope:FileContentResult)
    private static final MsgProto.FileContentResult DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new MsgProto.FileContentResult();
    }

    public static MsgProto.FileContentResult getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<FileContentResult>
        PARSER = new com.google.protobuf.AbstractParser<FileContentResult>() {
      @java.lang.Override
      public FileContentResult parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<FileContentResult> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<FileContentResult> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public MsgProto.FileContentResult getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_DpMessage_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_DpMessage_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_FileContentCmd_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_FileContentCmd_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_FileContentResult_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_FileContentResult_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\tmsg.proto\"\327\001\n\tDpMessage\022&\n\010msg_type\030\001 " +
      "\001(\0162\024.DpMessage.DpMsgType\022)\n\016fileContent" +
      "Cmd\030\002 \001(\0132\017.FileContentCmdH\000\022/\n\021fileCont" +
      "entResult\030\003 \001(\0132\022.FileContentResultH\000\":\n" +
      "\tDpMsgType\022\024\n\020FILE_CONTENT_CMD\020\000\022\027\n\023FILE" +
      "_CONTENT_RESULT\020\001B\n\n\010dataBody\"\"\n\016FileCon" +
      "tentCmd\022\020\n\010fileName\030\001 \001(\t\":\n\021FileContent" +
      "Result\022\020\n\010fileName\030\001 \001(\t\022\023\n\013fileContent\030" +
      "\002 \001(\tB\nB\010MsgProtob\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_DpMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_DpMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_DpMessage_descriptor,
        new java.lang.String[] { "MsgType", "FileContentCmd", "FileContentResult", "DataBody", });
    internal_static_FileContentCmd_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_FileContentCmd_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_FileContentCmd_descriptor,
        new java.lang.String[] { "FileName", });
    internal_static_FileContentResult_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_FileContentResult_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_FileContentResult_descriptor,
        new java.lang.String[] { "FileName", "FileContent", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
