// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: msg.proto
package com.enhui.netty.research.simple.common.proto;

public final class MsgProto {
    private MsgProto() {
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistryLite registry) {
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistry registry) {
        registerAllExtensions(
                (com.google.protobuf.ExtensionRegistryLite) registry);
    }

    /**
     * Protobuf enum {@code MsgCode}
     */
    public enum MsgCode
            implements com.google.protobuf.ProtocolMessageEnum {
        /**
         * <code>FILE_CONTENT_CMD = 0;</code>
         */
        FILE_CONTENT_CMD(0),
        /**
         * <code>FILE_CONTENT_RESULT = 1;</code>
         */
        FILE_CONTENT_RESULT(1),
        UNRECOGNIZED(-1),
        ;

        /**
         * <code>FILE_CONTENT_CMD = 0;</code>
         */
        public static final int FILE_CONTENT_CMD_VALUE = 0;
        /**
         * <code>FILE_CONTENT_RESULT = 1;</code>
         */
        public static final int FILE_CONTENT_RESULT_VALUE = 1;


        public final int getNumber() {
            if (this == UNRECOGNIZED) {
                throw new java.lang.IllegalArgumentException(
                        "Can't get the number of an unknown enum value.");
            }
            return value;
        }

        /**
         * @param value The numeric wire value of the corresponding enum entry.
         * @return The enum associated with the given numeric wire value.
         * @deprecated Use {@link #forNumber(int)} instead.
         */
        @java.lang.Deprecated
        public static MsgCode valueOf(int value) {
            return forNumber(value);
        }

        /**
         * @param value The numeric wire value of the corresponding enum entry.
         * @return The enum associated with the given numeric wire value.
         */
        public static MsgCode forNumber(int value) {
            switch (value) {
                case 0:
                    return FILE_CONTENT_CMD;
                case 1:
                    return FILE_CONTENT_RESULT;
                default:
                    return null;
            }
        }

        public static com.google.protobuf.Internal.EnumLiteMap<MsgCode>
        internalGetValueMap() {
            return internalValueMap;
        }

        private static final com.google.protobuf.Internal.EnumLiteMap<
                MsgCode> internalValueMap =
                new com.google.protobuf.Internal.EnumLiteMap<MsgCode>() {
                    public MsgCode findValueByNumber(int number) {
                        return MsgCode.forNumber(number);
                    }
                };

        public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
            if (this == UNRECOGNIZED) {
                throw new java.lang.IllegalStateException(
                        "Can't get the descriptor of an unrecognized enum value.");
            }
            return getDescriptor().getValues().get(ordinal());
        }

        public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
            return getDescriptor();
        }

        public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
            return MsgProto.getDescriptor().getEnumTypes().get(0);
        }

        private static final MsgCode[] VALUES = values();

        public static MsgCode valueOf(
                com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
            if (desc.getType() != getDescriptor()) {
                throw new java.lang.IllegalArgumentException(
                        "EnumValueDescriptor is not for this type.");
            }
            if (desc.getIndex() == -1) {
                return UNRECOGNIZED;
            }
            return VALUES[desc.getIndex()];
        }

        private final int value;

        private MsgCode(int value) {
            this.value = value;
        }

        // @@protoc_insertion_point(enum_scope:MsgCode)
    }

    public interface FileContentCmdOrBuilder extends
            // @@protoc_insertion_point(interface_extends:FileContentCmd)
            com.google.protobuf.MessageOrBuilder {

        /**
         * <pre>
         * 文件名称
         * </pre>
         *
         * <code>string fileName = 1;</code>
         *
         * @return The fileName.
         */
        java.lang.String getFileName();

        /**
         * <pre>
         * 文件名称
         * </pre>
         *
         * <code>string fileName = 1;</code>
         *
         * @return The bytes for fileName.
         */
        com.google.protobuf.ByteString
        getFileNameBytes();
    }

    /**
     * Protobuf type {@code FileContentCmd}
     */
    public static final class FileContentCmd extends
            com.google.protobuf.GeneratedMessageV3 implements
            // @@protoc_insertion_point(message_implements:FileContentCmd)
            FileContentCmdOrBuilder {
        private static final long serialVersionUID = 0L;

        // Use FileContentCmd.newBuilder() to construct.
        private FileContentCmd(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
            super(builder);
        }

        private FileContentCmd() {
            fileName_ = "";
        }

        @java.lang.Override
        @SuppressWarnings({"unused"})
        protected java.lang.Object newInstance(
                UnusedPrivateParameter unused) {
            return new FileContentCmd();
        }

        @java.lang.Override
        public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
            return this.unknownFields;
        }

        public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
            return MsgProto.internal_static_FileContentCmd_descriptor;
        }

        @java.lang.Override
        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
            return MsgProto.internal_static_FileContentCmd_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(
                            MsgProto.FileContentCmd.class, MsgProto.FileContentCmd.Builder.class);
        }

        public static final int FILENAME_FIELD_NUMBER = 1;
        @SuppressWarnings("serial")
        private volatile java.lang.Object fileName_ = "";

        /**
         * <pre>
         * 文件名称
         * </pre>
         *
         * <code>string fileName = 1;</code>
         *
         * @return The fileName.
         */
        @java.lang.Override
        public java.lang.String getFileName() {
            java.lang.Object ref = fileName_;
            if (ref instanceof java.lang.String) {
                return (java.lang.String) ref;
            } else {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                java.lang.String s = bs.toStringUtf8();
                fileName_ = s;
                return s;
            }
        }

        /**
         * <pre>
         * 文件名称
         * </pre>
         *
         * <code>string fileName = 1;</code>
         *
         * @return The bytes for fileName.
         */
        @java.lang.Override
        public com.google.protobuf.ByteString
        getFileNameBytes() {
            java.lang.Object ref = fileName_;
            if (ref instanceof java.lang.String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (java.lang.String) ref);
                fileName_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        private byte memoizedIsInitialized = -1;

        @java.lang.Override
        public final boolean isInitialized() {
            byte isInitialized = memoizedIsInitialized;
            if (isInitialized == 1) return true;
            if (isInitialized == 0) return false;

            memoizedIsInitialized = 1;
            return true;
        }

        @java.lang.Override
        public void writeTo(com.google.protobuf.CodedOutputStream output)
                throws java.io.IOException {
            if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(fileName_)) {
                com.google.protobuf.GeneratedMessageV3.writeString(output, 1, fileName_);
            }
            getUnknownFields().writeTo(output);
        }

        @java.lang.Override
        public int getSerializedSize() {
            int size = memoizedSize;
            if (size != -1) return size;

            size = 0;
            if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(fileName_)) {
                size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, fileName_);
            }
            size += getUnknownFields().getSerializedSize();
            memoizedSize = size;
            return size;
        }

        @java.lang.Override
        public boolean equals(final java.lang.Object obj) {
            if (obj == this) {
                return true;
            }
            if (!(obj instanceof MsgProto.FileContentCmd)) {
                return super.equals(obj);
            }
            MsgProto.FileContentCmd other = (MsgProto.FileContentCmd) obj;

            if (!getFileName()
                    .equals(other.getFileName())) return false;
            if (!getUnknownFields().equals(other.getUnknownFields())) return false;
            return true;
        }

        @java.lang.Override
        public int hashCode() {
            if (memoizedHashCode != 0) {
                return memoizedHashCode;
            }
            int hash = 41;
            hash = (19 * hash) + getDescriptor().hashCode();
            hash = (37 * hash) + FILENAME_FIELD_NUMBER;
            hash = (53 * hash) + getFileName().hashCode();
            hash = (29 * hash) + getUnknownFields().hashCode();
            memoizedHashCode = hash;
            return hash;
        }

        public static MsgProto.FileContentCmd parseFrom(
                java.nio.ByteBuffer data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static MsgProto.FileContentCmd parseFrom(
                java.nio.ByteBuffer data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static MsgProto.FileContentCmd parseFrom(
                com.google.protobuf.ByteString data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static MsgProto.FileContentCmd parseFrom(
                com.google.protobuf.ByteString data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static MsgProto.FileContentCmd parseFrom(byte[] data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static MsgProto.FileContentCmd parseFrom(
                byte[] data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static MsgProto.FileContentCmd parseFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }

        public static MsgProto.FileContentCmd parseFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        public static MsgProto.FileContentCmd parseDelimitedFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input);
        }

        public static MsgProto.FileContentCmd parseDelimitedFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
        }

        public static MsgProto.FileContentCmd parseFrom(
                com.google.protobuf.CodedInputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }

        public static MsgProto.FileContentCmd parseFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        @java.lang.Override
        public Builder newBuilderForType() {
            return newBuilder();
        }

        public static Builder newBuilder() {
            return DEFAULT_INSTANCE.toBuilder();
        }

        public static Builder newBuilder(MsgProto.FileContentCmd prototype) {
            return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
        }

        @java.lang.Override
        public Builder toBuilder() {
            return this == DEFAULT_INSTANCE
                    ? new Builder() : new Builder().mergeFrom(this);
        }

        @java.lang.Override
        protected Builder newBuilderForType(
                com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
            Builder builder = new Builder(parent);
            return builder;
        }

        /**
         * Protobuf type {@code FileContentCmd}
         */
        public static final class Builder extends
                com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
                // @@protoc_insertion_point(builder_implements:FileContentCmd)
                MsgProto.FileContentCmdOrBuilder {
            public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
                return MsgProto.internal_static_FileContentCmd_descriptor;
            }

            @java.lang.Override
            protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internalGetFieldAccessorTable() {
                return MsgProto.internal_static_FileContentCmd_fieldAccessorTable
                        .ensureFieldAccessorsInitialized(
                                MsgProto.FileContentCmd.class, MsgProto.FileContentCmd.Builder.class);
            }

            // Construct using MsgProto.FileContentCmd.newBuilder()
            private Builder() {

            }

            private Builder(
                    com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
                super(parent);

            }

            @java.lang.Override
            public Builder clear() {
                super.clear();
                bitField0_ = 0;
                fileName_ = "";
                return this;
            }

            @java.lang.Override
            public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
                return MsgProto.internal_static_FileContentCmd_descriptor;
            }

            @java.lang.Override
            public MsgProto.FileContentCmd getDefaultInstanceForType() {
                return MsgProto.FileContentCmd.getDefaultInstance();
            }

            @java.lang.Override
            public MsgProto.FileContentCmd build() {
                MsgProto.FileContentCmd result = buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(result);
                }
                return result;
            }

            @java.lang.Override
            public MsgProto.FileContentCmd buildPartial() {
                MsgProto.FileContentCmd result = new MsgProto.FileContentCmd(this);
                if (bitField0_ != 0) {
                    buildPartial0(result);
                }
                onBuilt();
                return result;
            }

            private void buildPartial0(MsgProto.FileContentCmd result) {
                int from_bitField0_ = bitField0_;
                if (((from_bitField0_ & 0x00000001) != 0)) {
                    result.fileName_ = fileName_;
                }
            }

            @java.lang.Override
            public Builder clone() {
                return super.clone();
            }

            @java.lang.Override
            public Builder setField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    java.lang.Object value) {
                return super.setField(field, value);
            }

            @java.lang.Override
            public Builder clearField(
                    com.google.protobuf.Descriptors.FieldDescriptor field) {
                return super.clearField(field);
            }

            @java.lang.Override
            public Builder clearOneof(
                    com.google.protobuf.Descriptors.OneofDescriptor oneof) {
                return super.clearOneof(oneof);
            }

            @java.lang.Override
            public Builder setRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    int index, java.lang.Object value) {
                return super.setRepeatedField(field, index, value);
            }

            @java.lang.Override
            public Builder addRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    java.lang.Object value) {
                return super.addRepeatedField(field, value);
            }

            @java.lang.Override
            public Builder mergeFrom(com.google.protobuf.Message other) {
                if (other instanceof MsgProto.FileContentCmd) {
                    return mergeFrom((MsgProto.FileContentCmd) other);
                } else {
                    super.mergeFrom(other);
                    return this;
                }
            }

            public Builder mergeFrom(MsgProto.FileContentCmd other) {
                if (other == MsgProto.FileContentCmd.getDefaultInstance()) return this;
                if (!other.getFileName().isEmpty()) {
                    fileName_ = other.fileName_;
                    bitField0_ |= 0x00000001;
                    onChanged();
                }
                this.mergeUnknownFields(other.getUnknownFields());
                onChanged();
                return this;
            }

            @java.lang.Override
            public final boolean isInitialized() {
                return true;
            }

            @java.lang.Override
            public Builder mergeFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws java.io.IOException {
                if (extensionRegistry == null) {
                    throw new java.lang.NullPointerException();
                }
                try {
                    boolean done = false;
                    while (!done) {
                        int tag = input.readTag();
                        switch (tag) {
                            case 0:
                                done = true;
                                break;
                            case 10: {
                                fileName_ = input.readStringRequireUtf8();
                                bitField0_ |= 0x00000001;
                                break;
                            } // case 10
                            default: {
                                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                                    done = true; // was an endgroup tag
                                }
                                break;
                            } // default:
                        } // switch (tag)
                    } // while (!done)
                } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                    throw e.unwrapIOException();
                } finally {
                    onChanged();
                } // finally
                return this;
            }

            private int bitField0_;

            private java.lang.Object fileName_ = "";

            /**
             * <pre>
             * 文件名称
             * </pre>
             *
             * <code>string fileName = 1;</code>
             *
             * @return The fileName.
             */
            public java.lang.String getFileName() {
                java.lang.Object ref = fileName_;
                if (!(ref instanceof java.lang.String)) {
                    com.google.protobuf.ByteString bs =
                            (com.google.protobuf.ByteString) ref;
                    java.lang.String s = bs.toStringUtf8();
                    fileName_ = s;
                    return s;
                } else {
                    return (java.lang.String) ref;
                }
            }

            /**
             * <pre>
             * 文件名称
             * </pre>
             *
             * <code>string fileName = 1;</code>
             *
             * @return The bytes for fileName.
             */
            public com.google.protobuf.ByteString
            getFileNameBytes() {
                java.lang.Object ref = fileName_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b =
                            com.google.protobuf.ByteString.copyFromUtf8(
                                    (java.lang.String) ref);
                    fileName_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }

            /**
             * <pre>
             * 文件名称
             * </pre>
             *
             * <code>string fileName = 1;</code>
             *
             * @param value The fileName to set.
             * @return This builder for chaining.
             */
            public Builder setFileName(
                    java.lang.String value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                fileName_ = value;
                bitField0_ |= 0x00000001;
                onChanged();
                return this;
            }

            /**
             * <pre>
             * 文件名称
             * </pre>
             *
             * <code>string fileName = 1;</code>
             *
             * @return This builder for chaining.
             */
            public Builder clearFileName() {
                fileName_ = getDefaultInstance().getFileName();
                bitField0_ = (bitField0_ & ~0x00000001);
                onChanged();
                return this;
            }

            /**
             * <pre>
             * 文件名称
             * </pre>
             *
             * <code>string fileName = 1;</code>
             *
             * @param value The bytes for fileName to set.
             * @return This builder for chaining.
             */
            public Builder setFileNameBytes(
                    com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                checkByteStringIsUtf8(value);
                fileName_ = value;
                bitField0_ |= 0x00000001;
                onChanged();
                return this;
            }

            @java.lang.Override
            public final Builder setUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return super.setUnknownFields(unknownFields);
            }

            @java.lang.Override
            public final Builder mergeUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return super.mergeUnknownFields(unknownFields);
            }


            // @@protoc_insertion_point(builder_scope:FileContentCmd)
        }

        // @@protoc_insertion_point(class_scope:FileContentCmd)
        private static final MsgProto.FileContentCmd DEFAULT_INSTANCE;

        static {
            DEFAULT_INSTANCE = new MsgProto.FileContentCmd();
        }

        public static MsgProto.FileContentCmd getDefaultInstance() {
            return DEFAULT_INSTANCE;
        }

        private static final com.google.protobuf.Parser<FileContentCmd>
                PARSER = new com.google.protobuf.AbstractParser<FileContentCmd>() {
            @java.lang.Override
            public FileContentCmd parsePartialFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws com.google.protobuf.InvalidProtocolBufferException {
                Builder builder = newBuilder();
                try {
                    builder.mergeFrom(input, extensionRegistry);
                } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                    throw e.setUnfinishedMessage(builder.buildPartial());
                } catch (com.google.protobuf.UninitializedMessageException e) {
                    throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
                } catch (java.io.IOException e) {
                    throw new com.google.protobuf.InvalidProtocolBufferException(e)
                            .setUnfinishedMessage(builder.buildPartial());
                }
                return builder.buildPartial();
            }
        };

        public static com.google.protobuf.Parser<FileContentCmd> parser() {
            return PARSER;
        }

        @java.lang.Override
        public com.google.protobuf.Parser<FileContentCmd> getParserForType() {
            return PARSER;
        }

        @java.lang.Override
        public MsgProto.FileContentCmd getDefaultInstanceForType() {
            return DEFAULT_INSTANCE;
        }

    }

    public interface FileContentResultOrBuilder extends
            // @@protoc_insertion_point(interface_extends:FileContentResult)
            com.google.protobuf.MessageOrBuilder {

        /**
         * <pre>
         * 文件名称
         * </pre>
         *
         * <code>string fileName = 1;</code>
         *
         * @return The fileName.
         */
        java.lang.String getFileName();

        /**
         * <pre>
         * 文件名称
         * </pre>
         *
         * <code>string fileName = 1;</code>
         *
         * @return The bytes for fileName.
         */
        com.google.protobuf.ByteString
        getFileNameBytes();

        /**
         * <pre>
         * 文件内容
         * </pre>
         *
         * <code>string fileContent = 2;</code>
         *
         * @return The fileContent.
         */
        java.lang.String getFileContent();

        /**
         * <pre>
         * 文件内容
         * </pre>
         *
         * <code>string fileContent = 2;</code>
         *
         * @return The bytes for fileContent.
         */
        com.google.protobuf.ByteString
        getFileContentBytes();
    }

    /**
     * Protobuf type {@code FileContentResult}
     */
    public static final class FileContentResult extends
            com.google.protobuf.GeneratedMessageV3 implements
            // @@protoc_insertion_point(message_implements:FileContentResult)
            FileContentResultOrBuilder {
        private static final long serialVersionUID = 0L;

        // Use FileContentResult.newBuilder() to construct.
        private FileContentResult(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
            super(builder);
        }

        private FileContentResult() {
            fileName_ = "";
            fileContent_ = "";
        }

        @java.lang.Override
        @SuppressWarnings({"unused"})
        protected java.lang.Object newInstance(
                UnusedPrivateParameter unused) {
            return new FileContentResult();
        }

        @java.lang.Override
        public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
            return this.unknownFields;
        }

        public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
            return MsgProto.internal_static_FileContentResult_descriptor;
        }

        @java.lang.Override
        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
            return MsgProto.internal_static_FileContentResult_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(
                            MsgProto.FileContentResult.class, MsgProto.FileContentResult.Builder.class);
        }

        public static final int FILENAME_FIELD_NUMBER = 1;
        @SuppressWarnings("serial")
        private volatile java.lang.Object fileName_ = "";

        /**
         * <pre>
         * 文件名称
         * </pre>
         *
         * <code>string fileName = 1;</code>
         *
         * @return The fileName.
         */
        @java.lang.Override
        public java.lang.String getFileName() {
            java.lang.Object ref = fileName_;
            if (ref instanceof java.lang.String) {
                return (java.lang.String) ref;
            } else {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                java.lang.String s = bs.toStringUtf8();
                fileName_ = s;
                return s;
            }
        }

        /**
         * <pre>
         * 文件名称
         * </pre>
         *
         * <code>string fileName = 1;</code>
         *
         * @return The bytes for fileName.
         */
        @java.lang.Override
        public com.google.protobuf.ByteString
        getFileNameBytes() {
            java.lang.Object ref = fileName_;
            if (ref instanceof java.lang.String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (java.lang.String) ref);
                fileName_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        public static final int FILECONTENT_FIELD_NUMBER = 2;
        @SuppressWarnings("serial")
        private volatile java.lang.Object fileContent_ = "";

        /**
         * <pre>
         * 文件内容
         * </pre>
         *
         * <code>string fileContent = 2;</code>
         *
         * @return The fileContent.
         */
        @java.lang.Override
        public java.lang.String getFileContent() {
            java.lang.Object ref = fileContent_;
            if (ref instanceof java.lang.String) {
                return (java.lang.String) ref;
            } else {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                java.lang.String s = bs.toStringUtf8();
                fileContent_ = s;
                return s;
            }
        }

        /**
         * <pre>
         * 文件内容
         * </pre>
         *
         * <code>string fileContent = 2;</code>
         *
         * @return The bytes for fileContent.
         */
        @java.lang.Override
        public com.google.protobuf.ByteString
        getFileContentBytes() {
            java.lang.Object ref = fileContent_;
            if (ref instanceof java.lang.String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (java.lang.String) ref);
                fileContent_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        private byte memoizedIsInitialized = -1;

        @java.lang.Override
        public final boolean isInitialized() {
            byte isInitialized = memoizedIsInitialized;
            if (isInitialized == 1) return true;
            if (isInitialized == 0) return false;

            memoizedIsInitialized = 1;
            return true;
        }

        @java.lang.Override
        public void writeTo(com.google.protobuf.CodedOutputStream output)
                throws java.io.IOException {
            if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(fileName_)) {
                com.google.protobuf.GeneratedMessageV3.writeString(output, 1, fileName_);
            }
            if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(fileContent_)) {
                com.google.protobuf.GeneratedMessageV3.writeString(output, 2, fileContent_);
            }
            getUnknownFields().writeTo(output);
        }

        @java.lang.Override
        public int getSerializedSize() {
            int size = memoizedSize;
            if (size != -1) return size;

            size = 0;
            if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(fileName_)) {
                size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, fileName_);
            }
            if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(fileContent_)) {
                size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, fileContent_);
            }
            size += getUnknownFields().getSerializedSize();
            memoizedSize = size;
            return size;
        }

        @java.lang.Override
        public boolean equals(final java.lang.Object obj) {
            if (obj == this) {
                return true;
            }
            if (!(obj instanceof MsgProto.FileContentResult)) {
                return super.equals(obj);
            }
            MsgProto.FileContentResult other = (MsgProto.FileContentResult) obj;

            if (!getFileName()
                    .equals(other.getFileName())) return false;
            if (!getFileContent()
                    .equals(other.getFileContent())) return false;
            if (!getUnknownFields().equals(other.getUnknownFields())) return false;
            return true;
        }

        @java.lang.Override
        public int hashCode() {
            if (memoizedHashCode != 0) {
                return memoizedHashCode;
            }
            int hash = 41;
            hash = (19 * hash) + getDescriptor().hashCode();
            hash = (37 * hash) + FILENAME_FIELD_NUMBER;
            hash = (53 * hash) + getFileName().hashCode();
            hash = (37 * hash) + FILECONTENT_FIELD_NUMBER;
            hash = (53 * hash) + getFileContent().hashCode();
            hash = (29 * hash) + getUnknownFields().hashCode();
            memoizedHashCode = hash;
            return hash;
        }

        public static MsgProto.FileContentResult parseFrom(
                java.nio.ByteBuffer data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static MsgProto.FileContentResult parseFrom(
                java.nio.ByteBuffer data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static MsgProto.FileContentResult parseFrom(
                com.google.protobuf.ByteString data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static MsgProto.FileContentResult parseFrom(
                com.google.protobuf.ByteString data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static MsgProto.FileContentResult parseFrom(byte[] data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static MsgProto.FileContentResult parseFrom(
                byte[] data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static MsgProto.FileContentResult parseFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }

        public static MsgProto.FileContentResult parseFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        public static MsgProto.FileContentResult parseDelimitedFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input);
        }

        public static MsgProto.FileContentResult parseDelimitedFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
        }

        public static MsgProto.FileContentResult parseFrom(
                com.google.protobuf.CodedInputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }

        public static MsgProto.FileContentResult parseFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        @java.lang.Override
        public Builder newBuilderForType() {
            return newBuilder();
        }

        public static Builder newBuilder() {
            return DEFAULT_INSTANCE.toBuilder();
        }

        public static Builder newBuilder(MsgProto.FileContentResult prototype) {
            return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
        }

        @java.lang.Override
        public Builder toBuilder() {
            return this == DEFAULT_INSTANCE
                    ? new Builder() : new Builder().mergeFrom(this);
        }

        @java.lang.Override
        protected Builder newBuilderForType(
                com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
            Builder builder = new Builder(parent);
            return builder;
        }

        /**
         * Protobuf type {@code FileContentResult}
         */
        public static final class Builder extends
                com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
                // @@protoc_insertion_point(builder_implements:FileContentResult)
                MsgProto.FileContentResultOrBuilder {
            public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
                return MsgProto.internal_static_FileContentResult_descriptor;
            }

            @java.lang.Override
            protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internalGetFieldAccessorTable() {
                return MsgProto.internal_static_FileContentResult_fieldAccessorTable
                        .ensureFieldAccessorsInitialized(
                                MsgProto.FileContentResult.class, MsgProto.FileContentResult.Builder.class);
            }

            // Construct using MsgProto.FileContentResult.newBuilder()
            private Builder() {

            }

            private Builder(
                    com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
                super(parent);

            }

            @java.lang.Override
            public Builder clear() {
                super.clear();
                bitField0_ = 0;
                fileName_ = "";
                fileContent_ = "";
                return this;
            }

            @java.lang.Override
            public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
                return MsgProto.internal_static_FileContentResult_descriptor;
            }

            @java.lang.Override
            public MsgProto.FileContentResult getDefaultInstanceForType() {
                return MsgProto.FileContentResult.getDefaultInstance();
            }

            @java.lang.Override
            public MsgProto.FileContentResult build() {
                MsgProto.FileContentResult result = buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(result);
                }
                return result;
            }

            @java.lang.Override
            public MsgProto.FileContentResult buildPartial() {
                MsgProto.FileContentResult result = new MsgProto.FileContentResult(this);
                if (bitField0_ != 0) {
                    buildPartial0(result);
                }
                onBuilt();
                return result;
            }

            private void buildPartial0(MsgProto.FileContentResult result) {
                int from_bitField0_ = bitField0_;
                if (((from_bitField0_ & 0x00000001) != 0)) {
                    result.fileName_ = fileName_;
                }
                if (((from_bitField0_ & 0x00000002) != 0)) {
                    result.fileContent_ = fileContent_;
                }
            }

            @java.lang.Override
            public Builder clone() {
                return super.clone();
            }

            @java.lang.Override
            public Builder setField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    java.lang.Object value) {
                return super.setField(field, value);
            }

            @java.lang.Override
            public Builder clearField(
                    com.google.protobuf.Descriptors.FieldDescriptor field) {
                return super.clearField(field);
            }

            @java.lang.Override
            public Builder clearOneof(
                    com.google.protobuf.Descriptors.OneofDescriptor oneof) {
                return super.clearOneof(oneof);
            }

            @java.lang.Override
            public Builder setRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    int index, java.lang.Object value) {
                return super.setRepeatedField(field, index, value);
            }

            @java.lang.Override
            public Builder addRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    java.lang.Object value) {
                return super.addRepeatedField(field, value);
            }

            @java.lang.Override
            public Builder mergeFrom(com.google.protobuf.Message other) {
                if (other instanceof MsgProto.FileContentResult) {
                    return mergeFrom((MsgProto.FileContentResult) other);
                } else {
                    super.mergeFrom(other);
                    return this;
                }
            }

            public Builder mergeFrom(MsgProto.FileContentResult other) {
                if (other == MsgProto.FileContentResult.getDefaultInstance()) return this;
                if (!other.getFileName().isEmpty()) {
                    fileName_ = other.fileName_;
                    bitField0_ |= 0x00000001;
                    onChanged();
                }
                if (!other.getFileContent().isEmpty()) {
                    fileContent_ = other.fileContent_;
                    bitField0_ |= 0x00000002;
                    onChanged();
                }
                this.mergeUnknownFields(other.getUnknownFields());
                onChanged();
                return this;
            }

            @java.lang.Override
            public final boolean isInitialized() {
                return true;
            }

            @java.lang.Override
            public Builder mergeFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws java.io.IOException {
                if (extensionRegistry == null) {
                    throw new java.lang.NullPointerException();
                }
                try {
                    boolean done = false;
                    while (!done) {
                        int tag = input.readTag();
                        switch (tag) {
                            case 0:
                                done = true;
                                break;
                            case 10: {
                                fileName_ = input.readStringRequireUtf8();
                                bitField0_ |= 0x00000001;
                                break;
                            } // case 10
                            case 18: {
                                fileContent_ = input.readStringRequireUtf8();
                                bitField0_ |= 0x00000002;
                                break;
                            } // case 18
                            default: {
                                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                                    done = true; // was an endgroup tag
                                }
                                break;
                            } // default:
                        } // switch (tag)
                    } // while (!done)
                } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                    throw e.unwrapIOException();
                } finally {
                    onChanged();
                } // finally
                return this;
            }

            private int bitField0_;

            private java.lang.Object fileName_ = "";

            /**
             * <pre>
             * 文件名称
             * </pre>
             *
             * <code>string fileName = 1;</code>
             *
             * @return The fileName.
             */
            public java.lang.String getFileName() {
                java.lang.Object ref = fileName_;
                if (!(ref instanceof java.lang.String)) {
                    com.google.protobuf.ByteString bs =
                            (com.google.protobuf.ByteString) ref;
                    java.lang.String s = bs.toStringUtf8();
                    fileName_ = s;
                    return s;
                } else {
                    return (java.lang.String) ref;
                }
            }

            /**
             * <pre>
             * 文件名称
             * </pre>
             *
             * <code>string fileName = 1;</code>
             *
             * @return The bytes for fileName.
             */
            public com.google.protobuf.ByteString
            getFileNameBytes() {
                java.lang.Object ref = fileName_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b =
                            com.google.protobuf.ByteString.copyFromUtf8(
                                    (java.lang.String) ref);
                    fileName_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }

            /**
             * <pre>
             * 文件名称
             * </pre>
             *
             * <code>string fileName = 1;</code>
             *
             * @param value The fileName to set.
             * @return This builder for chaining.
             */
            public Builder setFileName(
                    java.lang.String value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                fileName_ = value;
                bitField0_ |= 0x00000001;
                onChanged();
                return this;
            }

            /**
             * <pre>
             * 文件名称
             * </pre>
             *
             * <code>string fileName = 1;</code>
             *
             * @return This builder for chaining.
             */
            public Builder clearFileName() {
                fileName_ = getDefaultInstance().getFileName();
                bitField0_ = (bitField0_ & ~0x00000001);
                onChanged();
                return this;
            }

            /**
             * <pre>
             * 文件名称
             * </pre>
             *
             * <code>string fileName = 1;</code>
             *
             * @param value The bytes for fileName to set.
             * @return This builder for chaining.
             */
            public Builder setFileNameBytes(
                    com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                checkByteStringIsUtf8(value);
                fileName_ = value;
                bitField0_ |= 0x00000001;
                onChanged();
                return this;
            }

            private java.lang.Object fileContent_ = "";

            /**
             * <pre>
             * 文件内容
             * </pre>
             *
             * <code>string fileContent = 2;</code>
             *
             * @return The fileContent.
             */
            public java.lang.String getFileContent() {
                java.lang.Object ref = fileContent_;
                if (!(ref instanceof java.lang.String)) {
                    com.google.protobuf.ByteString bs =
                            (com.google.protobuf.ByteString) ref;
                    java.lang.String s = bs.toStringUtf8();
                    fileContent_ = s;
                    return s;
                } else {
                    return (java.lang.String) ref;
                }
            }

            /**
             * <pre>
             * 文件内容
             * </pre>
             *
             * <code>string fileContent = 2;</code>
             *
             * @return The bytes for fileContent.
             */
            public com.google.protobuf.ByteString
            getFileContentBytes() {
                java.lang.Object ref = fileContent_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b =
                            com.google.protobuf.ByteString.copyFromUtf8(
                                    (java.lang.String) ref);
                    fileContent_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }

            /**
             * <pre>
             * 文件内容
             * </pre>
             *
             * <code>string fileContent = 2;</code>
             *
             * @param value The fileContent to set.
             * @return This builder for chaining.
             */
            public Builder setFileContent(
                    java.lang.String value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                fileContent_ = value;
                bitField0_ |= 0x00000002;
                onChanged();
                return this;
            }

            /**
             * <pre>
             * 文件内容
             * </pre>
             *
             * <code>string fileContent = 2;</code>
             *
             * @return This builder for chaining.
             */
            public Builder clearFileContent() {
                fileContent_ = getDefaultInstance().getFileContent();
                bitField0_ = (bitField0_ & ~0x00000002);
                onChanged();
                return this;
            }

            /**
             * <pre>
             * 文件内容
             * </pre>
             *
             * <code>string fileContent = 2;</code>
             *
             * @param value The bytes for fileContent to set.
             * @return This builder for chaining.
             */
            public Builder setFileContentBytes(
                    com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                checkByteStringIsUtf8(value);
                fileContent_ = value;
                bitField0_ |= 0x00000002;
                onChanged();
                return this;
            }

            @java.lang.Override
            public final Builder setUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return super.setUnknownFields(unknownFields);
            }

            @java.lang.Override
            public final Builder mergeUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return super.mergeUnknownFields(unknownFields);
            }


            // @@protoc_insertion_point(builder_scope:FileContentResult)
        }

        // @@protoc_insertion_point(class_scope:FileContentResult)
        private static final MsgProto.FileContentResult DEFAULT_INSTANCE;

        static {
            DEFAULT_INSTANCE = new MsgProto.FileContentResult();
        }

        public static MsgProto.FileContentResult getDefaultInstance() {
            return DEFAULT_INSTANCE;
        }

        private static final com.google.protobuf.Parser<FileContentResult>
                PARSER = new com.google.protobuf.AbstractParser<FileContentResult>() {
            @java.lang.Override
            public FileContentResult parsePartialFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws com.google.protobuf.InvalidProtocolBufferException {
                Builder builder = newBuilder();
                try {
                    builder.mergeFrom(input, extensionRegistry);
                } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                    throw e.setUnfinishedMessage(builder.buildPartial());
                } catch (com.google.protobuf.UninitializedMessageException e) {
                    throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
                } catch (java.io.IOException e) {
                    throw new com.google.protobuf.InvalidProtocolBufferException(e)
                            .setUnfinishedMessage(builder.buildPartial());
                }
                return builder.buildPartial();
            }
        };

        public static com.google.protobuf.Parser<FileContentResult> parser() {
            return PARSER;
        }

        @java.lang.Override
        public com.google.protobuf.Parser<FileContentResult> getParserForType() {
            return PARSER;
        }

        @java.lang.Override
        public MsgProto.FileContentResult getDefaultInstanceForType() {
            return DEFAULT_INSTANCE;
        }

    }

    private static final com.google.protobuf.Descriptors.Descriptor
            internal_static_FileContentCmd_descriptor;
    private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internal_static_FileContentCmd_fieldAccessorTable;
    private static final com.google.protobuf.Descriptors.Descriptor
            internal_static_FileContentResult_descriptor;
    private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internal_static_FileContentResult_fieldAccessorTable;

    public static com.google.protobuf.Descriptors.FileDescriptor
    getDescriptor() {
        return descriptor;
    }

    private static com.google.protobuf.Descriptors.FileDescriptor
            descriptor;

    static {
        java.lang.String[] descriptorData = {
                "\n\tmsg.proto\"\"\n\016FileContentCmd\022\020\n\010fileNam" +
                        "e\030\001 \001(\t\":\n\021FileContentResult\022\020\n\010fileName" +
                        "\030\001 \001(\t\022\023\n\013fileContent\030\002 \001(\t*8\n\007MsgCode\022\024" +
                        "\n\020FILE_CONTENT_CMD\020\000\022\027\n\023FILE_CONTENT_RES" +
                        "ULT\020\001B\nB\010MsgProtob\006proto3"
        };
        descriptor = com.google.protobuf.Descriptors.FileDescriptor
                .internalBuildGeneratedFileFrom(descriptorData,
                        new com.google.protobuf.Descriptors.FileDescriptor[]{
                        });
        internal_static_FileContentCmd_descriptor =
                getDescriptor().getMessageTypes().get(0);
        internal_static_FileContentCmd_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_FileContentCmd_descriptor,
                new java.lang.String[]{"FileName",});
        internal_static_FileContentResult_descriptor =
                getDescriptor().getMessageTypes().get(1);
        internal_static_FileContentResult_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_FileContentResult_descriptor,
                new java.lang.String[]{"FileName", "FileContent",});
    }

    // @@protoc_insertion_point(outer_class_scope)
}
