package com.enhui.netty.research.rpc.common.proto;// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: rpc.proto

public final class RpcProto {
  private RpcProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface DpMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:DpMessage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int64 request_id = 1;</code>
     * @return The requestId.
     */
    long getRequestId();

    /**
     * <code>.DpMessage.DpMsgType msg_type = 2;</code>
     * @return The enum numeric value on the wire for msgType.
     */
    int getMsgTypeValue();
    /**
     * <code>.DpMessage.DpMsgType msg_type = 2;</code>
     * @return The msgType.
     */
    RpcProto.DpMessage.DpMsgType getMsgType();

    /**
     * <code>.FileContentCmd fileContentCmd = 3;</code>
     * @return Whether the fileContentCmd field is set.
     */
    boolean hasFileContentCmd();
    /**
     * <code>.FileContentCmd fileContentCmd = 3;</code>
     * @return The fileContentCmd.
     */
    RpcProto.FileContentCmd getFileContentCmd();
    /**
     * <code>.FileContentCmd fileContentCmd = 3;</code>
     */
    RpcProto.FileContentCmdOrBuilder getFileContentCmdOrBuilder();

    /**
     * <code>.FileContentResult fileContentResult = 4;</code>
     * @return Whether the fileContentResult field is set.
     */
    boolean hasFileContentResult();
    /**
     * <code>.FileContentResult fileContentResult = 4;</code>
     * @return The fileContentResult.
     */
    RpcProto.FileContentResult getFileContentResult();
    /**
     * <code>.FileContentResult fileContentResult = 4;</code>
     */
    RpcProto.FileContentResultOrBuilder getFileContentResultOrBuilder();

    public RpcProto.DpMessage.DataBodyCase getDataBodyCase();
  }
  /**
   * Protobuf type {@code DpMessage}
   */
  public static final class DpMessage extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:DpMessage)
      DpMessageOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use DpMessage.newBuilder() to construct.
    private DpMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private DpMessage() {
      msgType_ = 0;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new DpMessage();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return RpcProto.internal_static_DpMessage_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return RpcProto.internal_static_DpMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              RpcProto.DpMessage.class, RpcProto.DpMessage.Builder.class);
    }

    /**
     * Protobuf enum {@code DpMessage.DpMsgType}
     */
    public enum DpMsgType
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>FILE_CONTENT_CMD = 0;</code>
       */
      FILE_CONTENT_CMD(0),
      /**
       * <code>FILE_CONTENT_RESULT = 1;</code>
       */
      FILE_CONTENT_RESULT(1),
      UNRECOGNIZED(-1),
      ;

      /**
       * <code>FILE_CONTENT_CMD = 0;</code>
       */
      public static final int FILE_CONTENT_CMD_VALUE = 0;
      /**
       * <code>FILE_CONTENT_RESULT = 1;</code>
       */
      public static final int FILE_CONTENT_RESULT_VALUE = 1;


      public final int getNumber() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalArgumentException(
              "Can't get the number of an unknown enum value.");
        }
        return value;
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static DpMsgType valueOf(int value) {
        return forNumber(value);
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       */
      public static DpMsgType forNumber(int value) {
        switch (value) {
          case 0: return FILE_CONTENT_CMD;
          case 1: return FILE_CONTENT_RESULT;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<DpMsgType>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          DpMsgType> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<DpMsgType>() {
              public DpMsgType findValueByNumber(int number) {
                return DpMsgType.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalStateException(
              "Can't get the descriptor of an unrecognized enum value.");
        }
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return RpcProto.DpMessage.getDescriptor().getEnumTypes().get(0);
      }

      private static final DpMsgType[] VALUES = values();

      public static DpMsgType valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        if (desc.getIndex() == -1) {
          return UNRECOGNIZED;
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private DpMsgType(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:DpMessage.DpMsgType)
    }

    private int dataBodyCase_ = 0;
    private java.lang.Object dataBody_;
    public enum DataBodyCase
        implements com.google.protobuf.Internal.EnumLite,
            com.google.protobuf.AbstractMessage.InternalOneOfEnum {
      FILECONTENTCMD(3),
      FILECONTENTRESULT(4),
      DATABODY_NOT_SET(0);
      private final int value;
      private DataBodyCase(int value) {
        this.value = value;
      }
      /**
       * @param value The number of the enum to look for.
       * @return The enum associated with the given number.
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static DataBodyCase valueOf(int value) {
        return forNumber(value);
      }

      public static DataBodyCase forNumber(int value) {
        switch (value) {
          case 3: return FILECONTENTCMD;
          case 4: return FILECONTENTRESULT;
          case 0: return DATABODY_NOT_SET;
          default: return null;
        }
      }
      public int getNumber() {
        return this.value;
      }
    };

    public DataBodyCase
    getDataBodyCase() {
      return DataBodyCase.forNumber(
          dataBodyCase_);
    }

    public static final int REQUEST_ID_FIELD_NUMBER = 1;
    private long requestId_ = 0L;
    /**
     * <code>int64 request_id = 1;</code>
     * @return The requestId.
     */
    @java.lang.Override
    public long getRequestId() {
      return requestId_;
    }

    public static final int MSG_TYPE_FIELD_NUMBER = 2;
    private int msgType_ = 0;
    /**
     * <code>.DpMessage.DpMsgType msg_type = 2;</code>
     * @return The enum numeric value on the wire for msgType.
     */
    @java.lang.Override public int getMsgTypeValue() {
      return msgType_;
    }
    /**
     * <code>.DpMessage.DpMsgType msg_type = 2;</code>
     * @return The msgType.
     */
    @java.lang.Override public RpcProto.DpMessage.DpMsgType getMsgType() {
      RpcProto.DpMessage.DpMsgType result = RpcProto.DpMessage.DpMsgType.forNumber(msgType_);
      return result == null ? RpcProto.DpMessage.DpMsgType.UNRECOGNIZED : result;
    }

    public static final int FILECONTENTCMD_FIELD_NUMBER = 3;
    /**
     * <code>.FileContentCmd fileContentCmd = 3;</code>
     * @return Whether the fileContentCmd field is set.
     */
    @java.lang.Override
    public boolean hasFileContentCmd() {
      return dataBodyCase_ == 3;
    }
    /**
     * <code>.FileContentCmd fileContentCmd = 3;</code>
     * @return The fileContentCmd.
     */
    @java.lang.Override
    public RpcProto.FileContentCmd getFileContentCmd() {
      if (dataBodyCase_ == 3) {
         return (RpcProto.FileContentCmd) dataBody_;
      }
      return RpcProto.FileContentCmd.getDefaultInstance();
    }
    /**
     * <code>.FileContentCmd fileContentCmd = 3;</code>
     */
    @java.lang.Override
    public RpcProto.FileContentCmdOrBuilder getFileContentCmdOrBuilder() {
      if (dataBodyCase_ == 3) {
         return (RpcProto.FileContentCmd) dataBody_;
      }
      return RpcProto.FileContentCmd.getDefaultInstance();
    }

    public static final int FILECONTENTRESULT_FIELD_NUMBER = 4;
    /**
     * <code>.FileContentResult fileContentResult = 4;</code>
     * @return Whether the fileContentResult field is set.
     */
    @java.lang.Override
    public boolean hasFileContentResult() {
      return dataBodyCase_ == 4;
    }
    /**
     * <code>.FileContentResult fileContentResult = 4;</code>
     * @return The fileContentResult.
     */
    @java.lang.Override
    public RpcProto.FileContentResult getFileContentResult() {
      if (dataBodyCase_ == 4) {
         return (RpcProto.FileContentResult) dataBody_;
      }
      return RpcProto.FileContentResult.getDefaultInstance();
    }
    /**
     * <code>.FileContentResult fileContentResult = 4;</code>
     */
    @java.lang.Override
    public RpcProto.FileContentResultOrBuilder getFileContentResultOrBuilder() {
      if (dataBodyCase_ == 4) {
         return (RpcProto.FileContentResult) dataBody_;
      }
      return RpcProto.FileContentResult.getDefaultInstance();
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (requestId_ != 0L) {
        output.writeInt64(1, requestId_);
      }
      if (msgType_ != RpcProto.DpMessage.DpMsgType.FILE_CONTENT_CMD.getNumber()) {
        output.writeEnum(2, msgType_);
      }
      if (dataBodyCase_ == 3) {
        output.writeMessage(3, (RpcProto.FileContentCmd) dataBody_);
      }
      if (dataBodyCase_ == 4) {
        output.writeMessage(4, (RpcProto.FileContentResult) dataBody_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (requestId_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, requestId_);
      }
      if (msgType_ != RpcProto.DpMessage.DpMsgType.FILE_CONTENT_CMD.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(2, msgType_);
      }
      if (dataBodyCase_ == 3) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, (RpcProto.FileContentCmd) dataBody_);
      }
      if (dataBodyCase_ == 4) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, (RpcProto.FileContentResult) dataBody_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof RpcProto.DpMessage)) {
        return super.equals(obj);
      }
      RpcProto.DpMessage other = (RpcProto.DpMessage) obj;

      if (getRequestId()
          != other.getRequestId()) return false;
      if (msgType_ != other.msgType_) return false;
      if (!getDataBodyCase().equals(other.getDataBodyCase())) return false;
      switch (dataBodyCase_) {
        case 3:
          if (!getFileContentCmd()
              .equals(other.getFileContentCmd())) return false;
          break;
        case 4:
          if (!getFileContentResult()
              .equals(other.getFileContentResult())) return false;
          break;
        case 0:
        default:
      }
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + REQUEST_ID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getRequestId());
      hash = (37 * hash) + MSG_TYPE_FIELD_NUMBER;
      hash = (53 * hash) + msgType_;
      switch (dataBodyCase_) {
        case 3:
          hash = (37 * hash) + FILECONTENTCMD_FIELD_NUMBER;
          hash = (53 * hash) + getFileContentCmd().hashCode();
          break;
        case 4:
          hash = (37 * hash) + FILECONTENTRESULT_FIELD_NUMBER;
          hash = (53 * hash) + getFileContentResult().hashCode();
          break;
        case 0:
        default:
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static RpcProto.DpMessage parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static RpcProto.DpMessage parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static RpcProto.DpMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static RpcProto.DpMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static RpcProto.DpMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static RpcProto.DpMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static RpcProto.DpMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static RpcProto.DpMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static RpcProto.DpMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static RpcProto.DpMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static RpcProto.DpMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static RpcProto.DpMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(RpcProto.DpMessage prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code DpMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:DpMessage)
        RpcProto.DpMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return RpcProto.internal_static_DpMessage_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return RpcProto.internal_static_DpMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                RpcProto.DpMessage.class, RpcProto.DpMessage.Builder.class);
      }

      // Construct using RpcProto.DpMessage.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        requestId_ = 0L;
        msgType_ = 0;
        if (fileContentCmdBuilder_ != null) {
          fileContentCmdBuilder_.clear();
        }
        if (fileContentResultBuilder_ != null) {
          fileContentResultBuilder_.clear();
        }
        dataBodyCase_ = 0;
        dataBody_ = null;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return RpcProto.internal_static_DpMessage_descriptor;
      }

      @java.lang.Override
      public RpcProto.DpMessage getDefaultInstanceForType() {
        return RpcProto.DpMessage.getDefaultInstance();
      }

      @java.lang.Override
      public RpcProto.DpMessage build() {
        RpcProto.DpMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public RpcProto.DpMessage buildPartial() {
        RpcProto.DpMessage result = new RpcProto.DpMessage(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        buildPartialOneofs(result);
        onBuilt();
        return result;
      }

      private void buildPartial0(RpcProto.DpMessage result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.requestId_ = requestId_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.msgType_ = msgType_;
        }
      }

      private void buildPartialOneofs(RpcProto.DpMessage result) {
        result.dataBodyCase_ = dataBodyCase_;
        result.dataBody_ = this.dataBody_;
        if (dataBodyCase_ == 3 &&
            fileContentCmdBuilder_ != null) {
          result.dataBody_ = fileContentCmdBuilder_.build();
        }
        if (dataBodyCase_ == 4 &&
            fileContentResultBuilder_ != null) {
          result.dataBody_ = fileContentResultBuilder_.build();
        }
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof RpcProto.DpMessage) {
          return mergeFrom((RpcProto.DpMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(RpcProto.DpMessage other) {
        if (other == RpcProto.DpMessage.getDefaultInstance()) return this;
        if (other.getRequestId() != 0L) {
          setRequestId(other.getRequestId());
        }
        if (other.msgType_ != 0) {
          setMsgTypeValue(other.getMsgTypeValue());
        }
        switch (other.getDataBodyCase()) {
          case FILECONTENTCMD: {
            mergeFileContentCmd(other.getFileContentCmd());
            break;
          }
          case FILECONTENTRESULT: {
            mergeFileContentResult(other.getFileContentResult());
            break;
          }
          case DATABODY_NOT_SET: {
            break;
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                requestId_ = input.readInt64();
                bitField0_ |= 0x00000001;
                break;
              } // case 8
              case 16: {
                msgType_ = input.readEnum();
                bitField0_ |= 0x00000002;
                break;
              } // case 16
              case 26: {
                input.readMessage(
                    getFileContentCmdFieldBuilder().getBuilder(),
                    extensionRegistry);
                dataBodyCase_ = 3;
                break;
              } // case 26
              case 34: {
                input.readMessage(
                    getFileContentResultFieldBuilder().getBuilder(),
                    extensionRegistry);
                dataBodyCase_ = 4;
                break;
              } // case 34
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int dataBodyCase_ = 0;
      private java.lang.Object dataBody_;
      public DataBodyCase
          getDataBodyCase() {
        return DataBodyCase.forNumber(
            dataBodyCase_);
      }

      public Builder clearDataBody() {
        dataBodyCase_ = 0;
        dataBody_ = null;
        onChanged();
        return this;
      }

      private int bitField0_;

      private long requestId_ ;
      /**
       * <code>int64 request_id = 1;</code>
       * @return The requestId.
       */
      @java.lang.Override
      public long getRequestId() {
        return requestId_;
      }
      /**
       * <code>int64 request_id = 1;</code>
       * @param value The requestId to set.
       * @return This builder for chaining.
       */
      public Builder setRequestId(long value) {
        
        requestId_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>int64 request_id = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearRequestId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        requestId_ = 0L;
        onChanged();
        return this;
      }

      private int msgType_ = 0;
      /**
       * <code>.DpMessage.DpMsgType msg_type = 2;</code>
       * @return The enum numeric value on the wire for msgType.
       */
      @java.lang.Override public int getMsgTypeValue() {
        return msgType_;
      }
      /**
       * <code>.DpMessage.DpMsgType msg_type = 2;</code>
       * @param value The enum numeric value on the wire for msgType to set.
       * @return This builder for chaining.
       */
      public Builder setMsgTypeValue(int value) {
        msgType_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>.DpMessage.DpMsgType msg_type = 2;</code>
       * @return The msgType.
       */
      @java.lang.Override
      public RpcProto.DpMessage.DpMsgType getMsgType() {
        RpcProto.DpMessage.DpMsgType result = RpcProto.DpMessage.DpMsgType.forNumber(msgType_);
        return result == null ? RpcProto.DpMessage.DpMsgType.UNRECOGNIZED : result;
      }
      /**
       * <code>.DpMessage.DpMsgType msg_type = 2;</code>
       * @param value The msgType to set.
       * @return This builder for chaining.
       */
      public Builder setMsgType(RpcProto.DpMessage.DpMsgType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000002;
        msgType_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.DpMessage.DpMsgType msg_type = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearMsgType() {
        bitField0_ = (bitField0_ & ~0x00000002);
        msgType_ = 0;
        onChanged();
        return this;
      }

      private com.google.protobuf.SingleFieldBuilderV3<
          RpcProto.FileContentCmd, RpcProto.FileContentCmd.Builder, RpcProto.FileContentCmdOrBuilder> fileContentCmdBuilder_;
      /**
       * <code>.FileContentCmd fileContentCmd = 3;</code>
       * @return Whether the fileContentCmd field is set.
       */
      @java.lang.Override
      public boolean hasFileContentCmd() {
        return dataBodyCase_ == 3;
      }
      /**
       * <code>.FileContentCmd fileContentCmd = 3;</code>
       * @return The fileContentCmd.
       */
      @java.lang.Override
      public RpcProto.FileContentCmd getFileContentCmd() {
        if (fileContentCmdBuilder_ == null) {
          if (dataBodyCase_ == 3) {
            return (RpcProto.FileContentCmd) dataBody_;
          }
          return RpcProto.FileContentCmd.getDefaultInstance();
        } else {
          if (dataBodyCase_ == 3) {
            return fileContentCmdBuilder_.getMessage();
          }
          return RpcProto.FileContentCmd.getDefaultInstance();
        }
      }
      /**
       * <code>.FileContentCmd fileContentCmd = 3;</code>
       */
      public Builder setFileContentCmd(RpcProto.FileContentCmd value) {
        if (fileContentCmdBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          dataBody_ = value;
          onChanged();
        } else {
          fileContentCmdBuilder_.setMessage(value);
        }
        dataBodyCase_ = 3;
        return this;
      }
      /**
       * <code>.FileContentCmd fileContentCmd = 3;</code>
       */
      public Builder setFileContentCmd(
          RpcProto.FileContentCmd.Builder builderForValue) {
        if (fileContentCmdBuilder_ == null) {
          dataBody_ = builderForValue.build();
          onChanged();
        } else {
          fileContentCmdBuilder_.setMessage(builderForValue.build());
        }
        dataBodyCase_ = 3;
        return this;
      }
      /**
       * <code>.FileContentCmd fileContentCmd = 3;</code>
       */
      public Builder mergeFileContentCmd(RpcProto.FileContentCmd value) {
        if (fileContentCmdBuilder_ == null) {
          if (dataBodyCase_ == 3 &&
              dataBody_ != RpcProto.FileContentCmd.getDefaultInstance()) {
            dataBody_ = RpcProto.FileContentCmd.newBuilder((RpcProto.FileContentCmd) dataBody_)
                .mergeFrom(value).buildPartial();
          } else {
            dataBody_ = value;
          }
          onChanged();
        } else {
          if (dataBodyCase_ == 3) {
            fileContentCmdBuilder_.mergeFrom(value);
          } else {
            fileContentCmdBuilder_.setMessage(value);
          }
        }
        dataBodyCase_ = 3;
        return this;
      }
      /**
       * <code>.FileContentCmd fileContentCmd = 3;</code>
       */
      public Builder clearFileContentCmd() {
        if (fileContentCmdBuilder_ == null) {
          if (dataBodyCase_ == 3) {
            dataBodyCase_ = 0;
            dataBody_ = null;
            onChanged();
          }
        } else {
          if (dataBodyCase_ == 3) {
            dataBodyCase_ = 0;
            dataBody_ = null;
          }
          fileContentCmdBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>.FileContentCmd fileContentCmd = 3;</code>
       */
      public RpcProto.FileContentCmd.Builder getFileContentCmdBuilder() {
        return getFileContentCmdFieldBuilder().getBuilder();
      }
      /**
       * <code>.FileContentCmd fileContentCmd = 3;</code>
       */
      @java.lang.Override
      public RpcProto.FileContentCmdOrBuilder getFileContentCmdOrBuilder() {
        if ((dataBodyCase_ == 3) && (fileContentCmdBuilder_ != null)) {
          return fileContentCmdBuilder_.getMessageOrBuilder();
        } else {
          if (dataBodyCase_ == 3) {
            return (RpcProto.FileContentCmd) dataBody_;
          }
          return RpcProto.FileContentCmd.getDefaultInstance();
        }
      }
      /**
       * <code>.FileContentCmd fileContentCmd = 3;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          RpcProto.FileContentCmd, RpcProto.FileContentCmd.Builder, RpcProto.FileContentCmdOrBuilder> 
          getFileContentCmdFieldBuilder() {
        if (fileContentCmdBuilder_ == null) {
          if (!(dataBodyCase_ == 3)) {
            dataBody_ = RpcProto.FileContentCmd.getDefaultInstance();
          }
          fileContentCmdBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              RpcProto.FileContentCmd, RpcProto.FileContentCmd.Builder, RpcProto.FileContentCmdOrBuilder>(
                  (RpcProto.FileContentCmd) dataBody_,
                  getParentForChildren(),
                  isClean());
          dataBody_ = null;
        }
        dataBodyCase_ = 3;
        onChanged();
        return fileContentCmdBuilder_;
      }

      private com.google.protobuf.SingleFieldBuilderV3<
          RpcProto.FileContentResult, RpcProto.FileContentResult.Builder, RpcProto.FileContentResultOrBuilder> fileContentResultBuilder_;
      /**
       * <code>.FileContentResult fileContentResult = 4;</code>
       * @return Whether the fileContentResult field is set.
       */
      @java.lang.Override
      public boolean hasFileContentResult() {
        return dataBodyCase_ == 4;
      }
      /**
       * <code>.FileContentResult fileContentResult = 4;</code>
       * @return The fileContentResult.
       */
      @java.lang.Override
      public RpcProto.FileContentResult getFileContentResult() {
        if (fileContentResultBuilder_ == null) {
          if (dataBodyCase_ == 4) {
            return (RpcProto.FileContentResult) dataBody_;
          }
          return RpcProto.FileContentResult.getDefaultInstance();
        } else {
          if (dataBodyCase_ == 4) {
            return fileContentResultBuilder_.getMessage();
          }
          return RpcProto.FileContentResult.getDefaultInstance();
        }
      }
      /**
       * <code>.FileContentResult fileContentResult = 4;</code>
       */
      public Builder setFileContentResult(RpcProto.FileContentResult value) {
        if (fileContentResultBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          dataBody_ = value;
          onChanged();
        } else {
          fileContentResultBuilder_.setMessage(value);
        }
        dataBodyCase_ = 4;
        return this;
      }
      /**
       * <code>.FileContentResult fileContentResult = 4;</code>
       */
      public Builder setFileContentResult(
          RpcProto.FileContentResult.Builder builderForValue) {
        if (fileContentResultBuilder_ == null) {
          dataBody_ = builderForValue.build();
          onChanged();
        } else {
          fileContentResultBuilder_.setMessage(builderForValue.build());
        }
        dataBodyCase_ = 4;
        return this;
      }
      /**
       * <code>.FileContentResult fileContentResult = 4;</code>
       */
      public Builder mergeFileContentResult(RpcProto.FileContentResult value) {
        if (fileContentResultBuilder_ == null) {
          if (dataBodyCase_ == 4 &&
              dataBody_ != RpcProto.FileContentResult.getDefaultInstance()) {
            dataBody_ = RpcProto.FileContentResult.newBuilder((RpcProto.FileContentResult) dataBody_)
                .mergeFrom(value).buildPartial();
          } else {
            dataBody_ = value;
          }
          onChanged();
        } else {
          if (dataBodyCase_ == 4) {
            fileContentResultBuilder_.mergeFrom(value);
          } else {
            fileContentResultBuilder_.setMessage(value);
          }
        }
        dataBodyCase_ = 4;
        return this;
      }
      /**
       * <code>.FileContentResult fileContentResult = 4;</code>
       */
      public Builder clearFileContentResult() {
        if (fileContentResultBuilder_ == null) {
          if (dataBodyCase_ == 4) {
            dataBodyCase_ = 0;
            dataBody_ = null;
            onChanged();
          }
        } else {
          if (dataBodyCase_ == 4) {
            dataBodyCase_ = 0;
            dataBody_ = null;
          }
          fileContentResultBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>.FileContentResult fileContentResult = 4;</code>
       */
      public RpcProto.FileContentResult.Builder getFileContentResultBuilder() {
        return getFileContentResultFieldBuilder().getBuilder();
      }
      /**
       * <code>.FileContentResult fileContentResult = 4;</code>
       */
      @java.lang.Override
      public RpcProto.FileContentResultOrBuilder getFileContentResultOrBuilder() {
        if ((dataBodyCase_ == 4) && (fileContentResultBuilder_ != null)) {
          return fileContentResultBuilder_.getMessageOrBuilder();
        } else {
          if (dataBodyCase_ == 4) {
            return (RpcProto.FileContentResult) dataBody_;
          }
          return RpcProto.FileContentResult.getDefaultInstance();
        }
      }
      /**
       * <code>.FileContentResult fileContentResult = 4;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          RpcProto.FileContentResult, RpcProto.FileContentResult.Builder, RpcProto.FileContentResultOrBuilder> 
          getFileContentResultFieldBuilder() {
        if (fileContentResultBuilder_ == null) {
          if (!(dataBodyCase_ == 4)) {
            dataBody_ = RpcProto.FileContentResult.getDefaultInstance();
          }
          fileContentResultBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              RpcProto.FileContentResult, RpcProto.FileContentResult.Builder, RpcProto.FileContentResultOrBuilder>(
                  (RpcProto.FileContentResult) dataBody_,
                  getParentForChildren(),
                  isClean());
          dataBody_ = null;
        }
        dataBodyCase_ = 4;
        onChanged();
        return fileContentResultBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:DpMessage)
    }

    // @@protoc_insertion_point(class_scope:DpMessage)
    private static final RpcProto.DpMessage DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new RpcProto.DpMessage();
    }

    public static RpcProto.DpMessage getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<DpMessage>
        PARSER = new com.google.protobuf.AbstractParser<DpMessage>() {
      @java.lang.Override
      public DpMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<DpMessage> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<DpMessage> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public RpcProto.DpMessage getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface FileContentCmdOrBuilder extends
      // @@protoc_insertion_point(interface_extends:FileContentCmd)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * 文件名称
     * </pre>
     *
     * <code>string fileName = 1;</code>
     * @return The fileName.
     */
    java.lang.String getFileName();
    /**
     * <pre>
     * 文件名称
     * </pre>
     *
     * <code>string fileName = 1;</code>
     * @return The bytes for fileName.
     */
    com.google.protobuf.ByteString
        getFileNameBytes();
  }
  /**
   * Protobuf type {@code FileContentCmd}
   */
  public static final class FileContentCmd extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:FileContentCmd)
      FileContentCmdOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use FileContentCmd.newBuilder() to construct.
    private FileContentCmd(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private FileContentCmd() {
      fileName_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new FileContentCmd();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return RpcProto.internal_static_FileContentCmd_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return RpcProto.internal_static_FileContentCmd_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              RpcProto.FileContentCmd.class, RpcProto.FileContentCmd.Builder.class);
    }

    public static final int FILENAME_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private volatile java.lang.Object fileName_ = "";
    /**
     * <pre>
     * 文件名称
     * </pre>
     *
     * <code>string fileName = 1;</code>
     * @return The fileName.
     */
    @java.lang.Override
    public java.lang.String getFileName() {
      java.lang.Object ref = fileName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        fileName_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * 文件名称
     * </pre>
     *
     * <code>string fileName = 1;</code>
     * @return The bytes for fileName.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getFileNameBytes() {
      java.lang.Object ref = fileName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        fileName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(fileName_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, fileName_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(fileName_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, fileName_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof RpcProto.FileContentCmd)) {
        return super.equals(obj);
      }
      RpcProto.FileContentCmd other = (RpcProto.FileContentCmd) obj;

      if (!getFileName()
          .equals(other.getFileName())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + FILENAME_FIELD_NUMBER;
      hash = (53 * hash) + getFileName().hashCode();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static RpcProto.FileContentCmd parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static RpcProto.FileContentCmd parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static RpcProto.FileContentCmd parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static RpcProto.FileContentCmd parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static RpcProto.FileContentCmd parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static RpcProto.FileContentCmd parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static RpcProto.FileContentCmd parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static RpcProto.FileContentCmd parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static RpcProto.FileContentCmd parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static RpcProto.FileContentCmd parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static RpcProto.FileContentCmd parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static RpcProto.FileContentCmd parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(RpcProto.FileContentCmd prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code FileContentCmd}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:FileContentCmd)
        RpcProto.FileContentCmdOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return RpcProto.internal_static_FileContentCmd_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return RpcProto.internal_static_FileContentCmd_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                RpcProto.FileContentCmd.class, RpcProto.FileContentCmd.Builder.class);
      }

      // Construct using RpcProto.FileContentCmd.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        fileName_ = "";
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return RpcProto.internal_static_FileContentCmd_descriptor;
      }

      @java.lang.Override
      public RpcProto.FileContentCmd getDefaultInstanceForType() {
        return RpcProto.FileContentCmd.getDefaultInstance();
      }

      @java.lang.Override
      public RpcProto.FileContentCmd build() {
        RpcProto.FileContentCmd result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public RpcProto.FileContentCmd buildPartial() {
        RpcProto.FileContentCmd result = new RpcProto.FileContentCmd(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(RpcProto.FileContentCmd result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.fileName_ = fileName_;
        }
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof RpcProto.FileContentCmd) {
          return mergeFrom((RpcProto.FileContentCmd)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(RpcProto.FileContentCmd other) {
        if (other == RpcProto.FileContentCmd.getDefaultInstance()) return this;
        if (!other.getFileName().isEmpty()) {
          fileName_ = other.fileName_;
          bitField0_ |= 0x00000001;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                fileName_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.lang.Object fileName_ = "";
      /**
       * <pre>
       * 文件名称
       * </pre>
       *
       * <code>string fileName = 1;</code>
       * @return The fileName.
       */
      public java.lang.String getFileName() {
        java.lang.Object ref = fileName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          fileName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * 文件名称
       * </pre>
       *
       * <code>string fileName = 1;</code>
       * @return The bytes for fileName.
       */
      public com.google.protobuf.ByteString
          getFileNameBytes() {
        java.lang.Object ref = fileName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          fileName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * 文件名称
       * </pre>
       *
       * <code>string fileName = 1;</code>
       * @param value The fileName to set.
       * @return This builder for chaining.
       */
      public Builder setFileName(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        fileName_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 文件名称
       * </pre>
       *
       * <code>string fileName = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearFileName() {
        fileName_ = getDefaultInstance().getFileName();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 文件名称
       * </pre>
       *
       * <code>string fileName = 1;</code>
       * @param value The bytes for fileName to set.
       * @return This builder for chaining.
       */
      public Builder setFileNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        fileName_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:FileContentCmd)
    }

    // @@protoc_insertion_point(class_scope:FileContentCmd)
    private static final RpcProto.FileContentCmd DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new RpcProto.FileContentCmd();
    }

    public static RpcProto.FileContentCmd getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<FileContentCmd>
        PARSER = new com.google.protobuf.AbstractParser<FileContentCmd>() {
      @java.lang.Override
      public FileContentCmd parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<FileContentCmd> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<FileContentCmd> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public RpcProto.FileContentCmd getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface FileContentResultOrBuilder extends
      // @@protoc_insertion_point(interface_extends:FileContentResult)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * 文件名称
     * </pre>
     *
     * <code>string fileName = 1;</code>
     * @return The fileName.
     */
    java.lang.String getFileName();
    /**
     * <pre>
     * 文件名称
     * </pre>
     *
     * <code>string fileName = 1;</code>
     * @return The bytes for fileName.
     */
    com.google.protobuf.ByteString
        getFileNameBytes();

    /**
     * <pre>
     * 文件内容
     * </pre>
     *
     * <code>string fileContent = 2;</code>
     * @return The fileContent.
     */
    java.lang.String getFileContent();
    /**
     * <pre>
     * 文件内容
     * </pre>
     *
     * <code>string fileContent = 2;</code>
     * @return The bytes for fileContent.
     */
    com.google.protobuf.ByteString
        getFileContentBytes();
  }
  /**
   * Protobuf type {@code FileContentResult}
   */
  public static final class FileContentResult extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:FileContentResult)
      FileContentResultOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use FileContentResult.newBuilder() to construct.
    private FileContentResult(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private FileContentResult() {
      fileName_ = "";
      fileContent_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new FileContentResult();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return RpcProto.internal_static_FileContentResult_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return RpcProto.internal_static_FileContentResult_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              RpcProto.FileContentResult.class, RpcProto.FileContentResult.Builder.class);
    }

    public static final int FILENAME_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private volatile java.lang.Object fileName_ = "";
    /**
     * <pre>
     * 文件名称
     * </pre>
     *
     * <code>string fileName = 1;</code>
     * @return The fileName.
     */
    @java.lang.Override
    public java.lang.String getFileName() {
      java.lang.Object ref = fileName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        fileName_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * 文件名称
     * </pre>
     *
     * <code>string fileName = 1;</code>
     * @return The bytes for fileName.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getFileNameBytes() {
      java.lang.Object ref = fileName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        fileName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int FILECONTENT_FIELD_NUMBER = 2;
    @SuppressWarnings("serial")
    private volatile java.lang.Object fileContent_ = "";
    /**
     * <pre>
     * 文件内容
     * </pre>
     *
     * <code>string fileContent = 2;</code>
     * @return The fileContent.
     */
    @java.lang.Override
    public java.lang.String getFileContent() {
      java.lang.Object ref = fileContent_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        fileContent_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * 文件内容
     * </pre>
     *
     * <code>string fileContent = 2;</code>
     * @return The bytes for fileContent.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getFileContentBytes() {
      java.lang.Object ref = fileContent_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        fileContent_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(fileName_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, fileName_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(fileContent_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, fileContent_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(fileName_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, fileName_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(fileContent_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, fileContent_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof RpcProto.FileContentResult)) {
        return super.equals(obj);
      }
      RpcProto.FileContentResult other = (RpcProto.FileContentResult) obj;

      if (!getFileName()
          .equals(other.getFileName())) return false;
      if (!getFileContent()
          .equals(other.getFileContent())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + FILENAME_FIELD_NUMBER;
      hash = (53 * hash) + getFileName().hashCode();
      hash = (37 * hash) + FILECONTENT_FIELD_NUMBER;
      hash = (53 * hash) + getFileContent().hashCode();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static RpcProto.FileContentResult parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static RpcProto.FileContentResult parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static RpcProto.FileContentResult parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static RpcProto.FileContentResult parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static RpcProto.FileContentResult parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static RpcProto.FileContentResult parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static RpcProto.FileContentResult parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static RpcProto.FileContentResult parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static RpcProto.FileContentResult parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static RpcProto.FileContentResult parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static RpcProto.FileContentResult parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static RpcProto.FileContentResult parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(RpcProto.FileContentResult prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code FileContentResult}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:FileContentResult)
        RpcProto.FileContentResultOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return RpcProto.internal_static_FileContentResult_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return RpcProto.internal_static_FileContentResult_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                RpcProto.FileContentResult.class, RpcProto.FileContentResult.Builder.class);
      }

      // Construct using RpcProto.FileContentResult.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        fileName_ = "";
        fileContent_ = "";
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return RpcProto.internal_static_FileContentResult_descriptor;
      }

      @java.lang.Override
      public RpcProto.FileContentResult getDefaultInstanceForType() {
        return RpcProto.FileContentResult.getDefaultInstance();
      }

      @java.lang.Override
      public RpcProto.FileContentResult build() {
        RpcProto.FileContentResult result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public RpcProto.FileContentResult buildPartial() {
        RpcProto.FileContentResult result = new RpcProto.FileContentResult(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(RpcProto.FileContentResult result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.fileName_ = fileName_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.fileContent_ = fileContent_;
        }
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof RpcProto.FileContentResult) {
          return mergeFrom((RpcProto.FileContentResult)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(RpcProto.FileContentResult other) {
        if (other == RpcProto.FileContentResult.getDefaultInstance()) return this;
        if (!other.getFileName().isEmpty()) {
          fileName_ = other.fileName_;
          bitField0_ |= 0x00000001;
          onChanged();
        }
        if (!other.getFileContent().isEmpty()) {
          fileContent_ = other.fileContent_;
          bitField0_ |= 0x00000002;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                fileName_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              case 18: {
                fileContent_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000002;
                break;
              } // case 18
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.lang.Object fileName_ = "";
      /**
       * <pre>
       * 文件名称
       * </pre>
       *
       * <code>string fileName = 1;</code>
       * @return The fileName.
       */
      public java.lang.String getFileName() {
        java.lang.Object ref = fileName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          fileName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * 文件名称
       * </pre>
       *
       * <code>string fileName = 1;</code>
       * @return The bytes for fileName.
       */
      public com.google.protobuf.ByteString
          getFileNameBytes() {
        java.lang.Object ref = fileName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          fileName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * 文件名称
       * </pre>
       *
       * <code>string fileName = 1;</code>
       * @param value The fileName to set.
       * @return This builder for chaining.
       */
      public Builder setFileName(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        fileName_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 文件名称
       * </pre>
       *
       * <code>string fileName = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearFileName() {
        fileName_ = getDefaultInstance().getFileName();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 文件名称
       * </pre>
       *
       * <code>string fileName = 1;</code>
       * @param value The bytes for fileName to set.
       * @return This builder for chaining.
       */
      public Builder setFileNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        fileName_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }

      private java.lang.Object fileContent_ = "";
      /**
       * <pre>
       * 文件内容
       * </pre>
       *
       * <code>string fileContent = 2;</code>
       * @return The fileContent.
       */
      public java.lang.String getFileContent() {
        java.lang.Object ref = fileContent_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          fileContent_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * 文件内容
       * </pre>
       *
       * <code>string fileContent = 2;</code>
       * @return The bytes for fileContent.
       */
      public com.google.protobuf.ByteString
          getFileContentBytes() {
        java.lang.Object ref = fileContent_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          fileContent_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * 文件内容
       * </pre>
       *
       * <code>string fileContent = 2;</code>
       * @param value The fileContent to set.
       * @return This builder for chaining.
       */
      public Builder setFileContent(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        fileContent_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 文件内容
       * </pre>
       *
       * <code>string fileContent = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearFileContent() {
        fileContent_ = getDefaultInstance().getFileContent();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 文件内容
       * </pre>
       *
       * <code>string fileContent = 2;</code>
       * @param value The bytes for fileContent to set.
       * @return This builder for chaining.
       */
      public Builder setFileContentBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        fileContent_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:FileContentResult)
    }

    // @@protoc_insertion_point(class_scope:FileContentResult)
    private static final RpcProto.FileContentResult DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new RpcProto.FileContentResult();
    }

    public static RpcProto.FileContentResult getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<FileContentResult>
        PARSER = new com.google.protobuf.AbstractParser<FileContentResult>() {
      @java.lang.Override
      public FileContentResult parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<FileContentResult> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<FileContentResult> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public RpcProto.FileContentResult getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_DpMessage_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_DpMessage_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_FileContentCmd_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_FileContentCmd_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_FileContentResult_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_FileContentResult_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\trpc.proto\"\353\001\n\tDpMessage\022\022\n\nrequest_id\030" +
      "\001 \001(\003\022&\n\010msg_type\030\002 \001(\0162\024.DpMessage.DpMs" +
      "gType\022)\n\016fileContentCmd\030\003 \001(\0132\017.FileCont" +
      "entCmdH\000\022/\n\021fileContentResult\030\004 \001(\0132\022.Fi" +
      "leContentResultH\000\":\n\tDpMsgType\022\024\n\020FILE_C" +
      "ONTENT_CMD\020\000\022\027\n\023FILE_CONTENT_RESULT\020\001B\n\n" +
      "\010dataBody\"\"\n\016FileContentCmd\022\020\n\010fileName\030" +
      "\001 \001(\t\":\n\021FileContentResult\022\020\n\010fileName\030\001" +
      " \001(\t\022\023\n\013fileContent\030\002 \001(\tB\nB\010RpcProtob\006p" +
      "roto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_DpMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_DpMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_DpMessage_descriptor,
        new java.lang.String[] { "RequestId", "MsgType", "FileContentCmd", "FileContentResult", "DataBody", });
    internal_static_FileContentCmd_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_FileContentCmd_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_FileContentCmd_descriptor,
        new java.lang.String[] { "FileName", });
    internal_static_FileContentResult_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_FileContentResult_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_FileContentResult_descriptor,
        new java.lang.String[] { "FileName", "FileContent", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
